Add settings to configure SQLAlchemy connection pool size
PrefectHQ/prefect pull request #10348
Opened 2023-08-01 18:52 UTC by mattklein

Add settings for PREFECT_SQLALCHEMY_POOL_SIZE and PREFECT_SQLALCHEMY_MAX_OVERFLOW; when creating a SQLAlchemy engine, pass these as the pool_size and max_overflow kwargs

This is to address [this issue](https://github.com/PrefectHQ/prefect/issues/6492)
And these threads in the Prefect Slack: [one](https://prefect-community.slack.com/archives/CL09KU1K7/p1690780403118979), [two](https://prefect-community.slack.com/archives/CL09KU1K7/p1690279251610069)

The change here is to add the ability to configure the SQLAlchemy pool size using Prefect settings. Without this ability, Prefect Server creates a SQLAlchemy connection pool with the default settings for pool_size (5) and max_overflow (10). The result is that the Prefect Server is limited to only using a max of 15 database connections at a time, which is insufficient for heavier workloads.

I've tested this change with a locally running Prefect Server and have verified it has the desired effect.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

2023-08-01 22:11 UTC, justquick commented
@mattklein would like to get an idea of how you tested it locally to handle larger workloads.

what setting values did you use for pool and overflow size?

how many jobs did you throw at it?

2023-08-01 23:16 UTC, dowrickio commented
> 

@justquick I manually set to "pool_size=200, max_overflow=400" and that covered my needs.  The performance of the prefect server takes a massive hit and I had to increase my API timeout to something astronomical but I got the flow running.

2023-08-02 01:57 UTC, mattklein commented
> @mattklein would like to get an idea of how you tested it locally to handle larger workloads.
> 
> what setting values did you use for pool and overflow size?
> 
> how many jobs did you throw at it?

@justquick The extent of the testing I did locally was to confirm that 1) I could pass the new settings as environment variables via `prefect server start`, and 2) the settings I used were passed through to the SQLAlchemy engine at creation time. I didn’t perform any actual load testing of this with our production workload and haven't settled on what actual values we'd want for the settings.

For the time being we're running multiple instances of the Prefect Server behind a load balancer to ensure that the current small number of max DB connections isn't a bottleneck. (As we've heard other folks in the community are also doing.) If/when this PR gets accepted and released we'd plan to upgrade to that release and then be able to run fewer servers with each configured for a higher number of DB connections.

2023-08-07 01:02 UTC, maitlandmarshall commented
I'm facing the same issue as well. If we could configure pool_timeout as well that would help.

2023-08-16 15:57 UTC, mattklein commented
Here's another thread with a user running into the same issue:
https://prefect-community.slack.com/archives/CL09KU1K7/p1691370546008439

2023-08-16 15:57 UTC, mattklein commented
We've been running this patch in our production infrastructure for a while now and can confirm it works and has the desired effect

2023-08-25 15:05 UTC, desertaxle requested changes
Thanks for the PR @mattklein! I have a couple of suggestions for the new setting descriptions, but this looks great overall!

2023-08-25 15:05 UTC, desertaxle commented on src/prefect/settings.py
> +default it to 5.
```suggestion
Controls connection pool size when using a PostgreSQL database with the Prefect API. If not set, the default SQLAlchemy pool size will be used.
```

2023-08-25 15:05 UTC, desertaxle commented on src/prefect/settings.py
> +"""
```suggestion
"""
Controls maximum overflow of the connection pool when using a PostgreSQL database with the Prefect API. If not set, the default SQLAlchemy maximum overflow value will be used.
"""
```

2023-08-25 16:07 UTC, mattklein commented
> Thanks for the PR @mattklein! I have a couple of suggestions for the new setting descriptions, but this looks great overall!

Thanks @desertaxle. I committed those changes you made, please re-review?

2023-08-28 14:14 UTC, desertaxle approved these changes
LGTM!

2023-08-28 14:17 UTC, desertaxle requested changes
@mattklein it looks like this PR is failing static analysis. Can you run `pre-commit run --all-files` locally and then commit the changes? This PR will be good to merge after that!

2023-08-30 22:16 UTC, desertaxle approved these changes
Thanks!

2023-08-30 22:16 UTC, merged