add discord notification block
PrefectHQ/prefect pull request #10394
Opened 2023-08-13 06:18 UTC by vishalsanfran

<img width="1477" alt="Screenshot 2023-08-12 at 11 04 21 PM" src="https://github.com/vishalsanfran/prefect/assets/7243915/049048dc-42fe-4c2e-95c6-73c3aec2b378">

Adds a DiscordWebhook notification block using the AbstractAppriseNotificationBlock

Closes #8727

### Example
```
In [1]: from prefect.blocks.notifications import DiscordWebhook

In [2]: discord_webhook_block = DiscordWebhook.load("discord-prefect")

In [3]: discord_webhook_block.notify("Hello from Prefect!!")
```

<img width="765" alt="Screenshot 2023-08-12 at 11 11 50 PM" src="https://github.com/vishalsanfran/prefect/assets/7243915/ed262424-fe26-42cd-b232-ba56e99db0c5">

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [x] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

2023-08-16 04:21 UTC, vishalsanfran commented
@zzstoatzz thanks, updated PR to change mattermost references to discord

2023-08-18 18:02 UTC, vishalsanfran commented
@zzstoatzz I had to use a different logo image as that the one provided was not square in shape and that was failing the tests.
Please allow the other workflows to run.

2023-08-21 22:04 UTC, zzstoatzz requested changes
nice! looking good, just a couple nits on fields descriptions

2023-08-21 22:04 UTC, zzstoatzz commented on src/prefect/blocks/notifications.py
> +            "Over-ride the default discord avatar icon and replace it with one identify"
```suggestion
            "Whether to override the default discord avatar icon."
```

2023-08-21 22:04 UTC, zzstoatzz commented on src/prefect/blocks/notifications.py
> +            "Include an image in-line with the message describing the notification"
```suggestion
            "Whether to include an image in-line with the message describing the notification"
```

2023-08-21 22:04 UTC, zzstoatzz commented on src/prefect/blocks/notifications.py
> +        description="Enable Text-To-Speech.",
```suggestion
        description="Whether to enable Text-To-Speech.",
```

2023-08-21 22:40 UTC, vishalsanfran commented on src/prefect/blocks/notifications.py
> +        description="Enable Text-To-Speech.",
updated

2023-08-21 22:40 UTC, vishalsanfran commented on src/prefect/blocks/notifications.py
> +            "Include an image in-line with the message describing the notification"
updated

2023-08-21 22:50 UTC, zzstoatzz commented
@vishalsanfran cool. We're [failing a pre-commit check](https://github.com/PrefectHQ/prefect/actions/runs/5932236782/job/16085676702?pr=10394) (do `pre-commit run .` locally) but once that's passing I think this is good to go!

2023-08-22 17:20 UTC, vishalsanfran commented
Sorry, this got closed accidentally as I was trying to rebase

2023-08-22 18:01 UTC, zzstoatzz approved these changes
nice! thank you for contributing

ruff is complaining about an unused import unrelated to this PR's changes, similarly the failing test is not related to this PR

2023-08-22 18:04 UTC, merged

2023-08-22 22:54 UTC, vishalsanfran commented
thanks! I'll look for more issues, but if there is anything specific you need help with, feel free to tag me.