Docs deployment concepts
PrefectHQ/prefect pull request #10392
Opened 2023-08-12 19:26 UTC by marwan116

This PR includes a very small documentation fix for the deployment concepts documentation page.

### Example

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [x] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

2023-08-14 12:41 UTC, billpalombi commented
Good catch @marwan116.

You're correct that `image_tag` should be just `tag`, but I believe `image_name` is correct.

2023-08-14 12:42 UTC, billpalombi requested changes

2023-08-14 13:05 UTC, marwan116 commented on docs/concepts/deployments.md
> +So long as our `build` steps produce fields called `image` and `tag`, every time we deploy a new version of our deployment these fields will be dynamically populated with the relevant values.
so {{build-image.image}} is what is used as a job_variable, it is what I understood to be a "produced field" in that it takes the image name and tag and produces the full image reference

2023-08-23 14:29 UTC, billpalombi approved these changes
Merging and following up with other changes in a seperate PR

2023-08-23 14:29 UTC, billpalombi commented on docs/concepts/deployments.md
> +So long as our `build` steps produce fields called `image` and `tag`, every time we deploy a new version of our deployment these fields will be dynamically populated with the relevant values.
I see. Your interpretation makes sense. This entire sentence is not clearly written. I'll rephrase to make it clearer.

2023-08-23 14:29 UTC, closed without merging