Automations Guide
PrefectHQ/prefect pull request #10559
Opened 2023-08-30 14:51 UTC by Sahiler

### Example

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [X] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [X] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

2023-10-06 14:55 UTC, WillRaphaelson commented
This isn't showing up in the deploy preview for me @Sahiler

2023-10-06 18:59 UTC, Sahiler commented
Updating the images with dark mode rq - keep a lookout for a change!

2023-10-09 16:14 UTC, WillRaphaelson requested changes

2023-10-09 16:14 UTC, WillRaphaelson commented on docs/guides/automations.md
> +!!! Warning "Available only on Prefect Cloud"
this is the wrong formatting

![image](https://github.com/PrefectHQ/prefect/assets/26799928/59017e10-8efd-4fea-9081-d2766e463e6d)

2023-10-09 16:14 UTC, WillRaphaelson commented on docs/guides/automations.md
> +In this guide, we will showcase common usecases where automations can shine when responding to your workflows. First we will create a simple notification automation in just a few UI clicks. Then buil
this may be clearer as bullets. id also remove extraneous language

2023-10-09 16:14 UTC, WillRaphaelson commented on docs/guides/automations.md
> +For example, let us try to grab data from an API and have a notification get kicked off of our end state.
based on the end state?

2023-10-09 16:14 UTC, WillRaphaelson commented on docs/guides/automations.md
> +1. Prior to creating the automation, let us confirm the notification location. We have to create a notification block to help define where the notification will be thrown.
i think you can use the word sent here. thrown signals error imo

2023-10-09 16:14 UTC, WillRaphaelson commented on docs/guides/automations.md
> +!!! Tip "No deployment created"
wrong formatting

2023-10-09 16:14 UTC, WillRaphaelson commented on docs/guides/automations.md
> +## Using an underlying .yaml file
i think both the python script and this should just be scrapped for using the triggers key on prefect.yaml

2023-10-10 14:41 UTC, Sahiler commented
Awesome thank you for all the feedback @WillRaphaelson! Going to take a look at them today

2023-10-10 15:23 UTC, seanpwlms commented on docs/guides/automations.md
> +Let us have local deployment created where we can kick off some work based on how long a flow is running. For example, if the `build_names` flow is taking to long to execute, we can kick off a deploy
```suggestion
Let us have local deployment created where we can kick off some work based on how long a flow is running. For example, if the `build_names` flow is taking too long to execute, we can kick off a deployment of the same flow `build_names` but replace the count value with something less.
```

2023-10-10 15:24 UTC, seanpwlms commented on docs/guides/automations.md
> +Now lets grab our `deployment_id` from this deployment, and embed it in our automation. There are a wide variety ways to obtain the `deployment_id`, but the CLI can be the quick way to see all of the
```suggestion
Now let's grab our `deployment_id` from this deployment, and embed it in our automation. There are a wide variety ways to obtain the `deployment_id`, but the CLI can be the quickest way to see all of the id's of your deployments. 
```

2023-10-10 15:26 UTC, seanpwlms commented on docs/guides/automations.md
> +Lets take this idea one step further, by creating a deployment that will be triggered from a previous flow taking longer than expected. We can take advantage of [Marvin](https://www.askmarvin.ai/) th
```suggestion
Let's take this idea one step further, by creating a deployment that will be triggered from a previous flow taking longer than expected. We can take advantage of [Marvin](https://www.askmarvin.ai/) that will help classify the data we are pulling in. Marvin is great in embedding data science and data analysis applications within your pre-existing data engineering worklows. In this case, we can use [Marvin AI functions](https://www.askmarvin.ai/components/ai_function/#ai-function) to help make our dataset more information rich. You can find more on potential usecases with Marvin on their page. 
```

2023-10-10 15:36 UTC, swilliams-graniterock commented on docs/guides/automations.md
> +Let us look at this example below using Marvin's AI functions. We will be taking in a dataframe and use the ai function to start analyzing some of the work.
```suggestion
Let us look at this example below using Marvin's AI functions. We will be taking in a dataframe and use the AI function to start analyzing some of the work. 
```

2023-10-16 17:10 UTC, discdiver requested changes
Will be good to have the automations guide in the docs. Thanks, Sahil!

2023-11-10 21:48 UTC, discdiver requested changes
Coming along! I think the notification automation example is good. 

I think showing how to go from custom event with a webhook to to an automation that kicks off a deployment with parameters passed into the flow would be good unless you think it's covered elsewhere in the main docs (outside recipes and blogs).  

Using the API to update an automation is a pretty advanced use case. I'd put that last.

Nice to see an example with triggers!

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +From the [Automations tutorial](https://docs.prefect.io/2.14.2/concepts/automations/), we were able to see the capabilities of what an automation can do and how to configure them within the UI.
```suggestion
From the [Automations tutorial](/concepts/automations/), we were able to see the capabilities of what an automation can do and how to configure them within the UI. 
```

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +From the [Automations tutorial](https://docs.prefect.io/2.14.2/concepts/automations/), we were able to see the capabilities of what an automation can do and how to configure them within the UI.
This is a link to concepts page - but a tutorial is mentioned.

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +        Automations are only available on Prefect Cloud, please refer to the [Cloud documentation](https://docs.prefect.io/2.13.4/cloud/#welcome-to-prefect-cloud) to see what
Use links that mkdocs will automatically resolve like this: `(/cloud/index/)`

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +        additional features are available such as Events and webhooks!
I think they should be other lowercase. You'll be showing events and webhooks here I assume, so probably don't want to send folks elsewhere, so maybe just say "to see what other features are available" or something like that.

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +## Creating the test script
Test script makes me think it will be for a test, so maybe something else.

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +
I'd add a prerequisites section here - some other guides that have step-by-step instructions have and it can be good for users.

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +```yaml
Could you please add a tab that uses deploy? Should just be the name = main block for the script above. Making that the default should cut down on the amount of work the user needs to do.

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +We can extend this idea one step further by utilizing our own .yaml interpretation of the automation, and registering that file with our UI. This simplifies the requirements of the automation by decl
I think you want a different term than "interpretation"

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +We can then have a helper function that helps apply this .yaml file with the rest api function.
```suggestion
We can then have a helper function that applies this YAML file with the REST API function. 
```

2023-11-10 21:48 UTC, discdiver commented on docs/guides/automations.md
> +        Keep in mind, we did not need to create a deployment to trigger our automation, where a state outcome of a local flow run helped trigger this notification block. We are not tied to creating a
```suggestion
    Keep in mind, we did not need to create a deployment to trigger our automation, where a state outcome of a local flow run helped trigger this notification block. We are not tied to creating a full deployment in order to have safe responses to our desired outcomes.
```

2023-11-10 21:48 UTC, discdiver commented on mkdocs.yml
> +          - Profiles & Configuration: guides/settings.md
See note above.

2023-11-14 18:39 UTC, Sahiler commented
Thank you for the comments @discdiver! Going to add in webhook example and flush out your syntax comments by EOW

2023-12-08 16:24 UTC, billpalombi commented
Looks like we've been going back and forth on this one for a while now. @Sahiler, @WillRaphaelson, and @discdiver, lets try to get this merged or closed by 12/22. If there's content that we still want to discuss or don't think is ready, lets strip it out and treat it as a seperate PR.

2024-01-08 23:15 UTC, discdiver requested changes
Thank you for the changes. I think it's getting close.

2024-01-08 23:15 UTC, discdiver commented on docs/guides/automations.md
> +## Using triggers, an AI function extension
```suggestion
## Using triggers
```

2024-01-08 23:15 UTC, discdiver commented on docs/guides/automations.md
> +In the next section, we will explore event triggers that can help kick off a deployment.
```suggestion
In the next section, we will explore event triggers that automate the kickoff of a deployment run.
```

2024-01-08 23:15 UTC, discdiver commented on docs/guides/automations.md
> +Marvin allows us to extend our current workflows by offering robust data science applications without more maintenance. This offers a lightweight framework in responding to changes in your orchestrat
You've seen how to 
```suggestion
## Next steps

You've seen how to create automations via the UI, REST API, and a triggers defined in a `prefect.yaml` deployment definition.

To learn more about events that can act as automation triggers, see the [events docs](/concepts/events/).  To learn more about event webhooks in particular, see the [webhooks guide](/guides/webhooks/)
```

2024-01-09 20:10 UTC, discdiver commented on docs/guides/automations.md
> +Let's take this idea one step further, by creating a deployment that will be triggered from a previous flow taking longer than expected. We can take advantage of Prefect's [Marvin](https://www.askmar
```suggestion
Let's take this idea one step further, by creating a deployment that will be triggered when a flow run takes longer than expected. We can take advantage of Prefect's [Marvin](https://www.askmarvin.ai/) library that will use an LLM to classify the data we. Marvin is great at embedding data science and data analysis applications within your pre-existing data engineering workflows. In this case, we can use [Marvin AI functions](https://www.askmarvin.ai/components/ai_function/#ai-function) to help make our dataset more information rich. 
```

2024-01-09 20:15 UTC, discdiver commented on docs/guides/automations.md
> +Let's take this idea one step further, by creating a deployment that will be triggered when a flow run takes longer than expected. We can take advantage of Prefect's [Marvin](https://www.askmarvin.ai
```suggestion
Let's take this idea one step further, by creating a deployment that will be triggered when a flow run takes longer than expected. 
We can take advantage of Prefect's [Marvin](https://www.askmarvin.ai/) library that will use an LLM to classify our data. 
Marvin is great at embedding data science and data analysis applications within your pre-existing data engineering workflows. In this case, we can use [Marvin'd AI functions](https://www.askmarvin.ai/components/ai_function/#ai-function) to help make our dataset more information rich. 

Install Marvin with `pip install marvin` and set you OpenAI API key as shown [here](https://www.askmarvin.ai/welcome/quickstart/)
```

2024-01-09 20:16 UTC, discdiver approved these changes
lgtm

2024-01-09 20:25 UTC, discdiver commented on docs/guides/automations.md
> +        Automations are a [Prefect Cloud](/cloud/) feature
```suggestion
        Automations are a [Prefect Cloud](/cloud/index/) feature
```

2024-01-09 20:26 UTC, discdiver commented on docs/guides/automations.md
> +=== ".yaml"
```suggestion
=== "prefect.yaml"
```

2024-01-09 20:36 UTC, discdiver commented on docs/guides/automations.md
> +        Automations are a [Prefect Cloud](/cloud/index/) feature
```suggestion
        Automations are a [Prefect Cloud](https://app.prefect.cloud) feature.
```

2024-01-09 20:48 UTC, discdiver commented on docs/guides/automations.md
> +        Automations are a [Prefect Cloud](https://app.prefect.cloud) feature.
```suggestion
        Automations are a Prefect Cloud feature.
```

2024-01-09 20:49 UTC, discdiver commented on docs/guides/automations.md
> +You can find a complete repo with these examples in our [recipes repository](https://github.com/EmilRex/prefect-api-examples/tree/main).
```suggestion
You can find a complete repo with these APIs examples in this [GitHub repository](https://github.com/EmilRex/prefect-api-examples/tree/main). 
```

2024-01-09 20:55 UTC, Sahiler commented
LGTM!

2024-01-09 20:56 UTC, merged