Adding a more readable error in case Docker not running
PrefectHQ/prefect pull request #12045
Opened 2024-02-21 19:17 UTC by eladm26

### Example

When deploying using a Docker image we get an unclear error in case Docker is not running on the local machine.
Added a more readable error Runtime Exception: `Docker is not running. please run docker and try again`

### Checklist

- [x] This pull request references any related issue by including "closes #11802"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
  

For documentation changes:

- [ ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed.

For new functions or classes in the Python SDK:

- [ ] This pull request includes helpful docstrings.
- [ ] If a new Python file was added, this pull request contains a stub page in the Python SDK docs and an entry in `mkdocs.yml` navigation.

2024-02-21 20:30 UTC, eladm26 commented on src/prefect/utilities/dockerutils.py
> +        raise RuntimeError("Docker is not running. please run docker and try again") from exc
[fixing error message](https://github.com/PrefectHQ/prefect/pull/12045/commits/715b55b074ddcc7b6f983ec85baf461525b4887f)

2024-02-22 00:20 UTC, zzstoatzz requested changes
somewhat pedantic comment about wording, just because the user might only see this message through the CLI, so they might not really have "code" to re-run directly.

otherwise, lgtm! 🙂

2024-02-22 00:20 UTC, zzstoatzz commented on src/prefect/utilities/dockerutils.py
> +            "This error is likely caused because Docker is not running. Please start Docker and rerun your code."
```suggestion
            "This error is often thrown because Docker is not running. Please ensure Docker is running."
```

2024-02-22 00:23 UTC, zzstoatzz approved these changes
thank you @eladm26 for the contribution 🎉

2024-02-22 15:13 UTC, merged