Add root flow run id to runtime
PrefectHQ/prefect pull request #13165
Opened 2024-04-30 11:58 UTC by 50Bytes-dev

This PR adds `root_flow_run_id` variable to `prefect.runtime.flow_run`.

### Example

```python
from prefect import flow
from prefect import runtime

@flow(log_prints=True)
def root_flow(x):
    child_flow()

@flow
def child_flow():
    deep_flow()

@flow
def deep_flow():
    print("Root flow run id is", runtime.flow_run.root_flow_run_id)

root_flow(1)
```

### Checklist

- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] If this pull request adds new functionality, it includes unit tests that cover the changes
- [x] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.

2024-05-18 06:10 UTC, 50Bytes-dev commented
@abrookins please merge, I need this

2024-06-01 11:18 UTC, 50Bytes-dev commented
Please merge this pull request

2024-06-08 08:30 UTC, 50Bytes-dev commented
UP

2024-06-21 04:15 UTC, 50Bytes-dev commented
Please review

2024-07-12 20:27 UTC, desertaxle requested changes

2024-07-12 20:27 UTC, desertaxle commented on .github/workflows/prefect-client.yml
> +name: Verify prefect-client build
Can you please remove this file from this PR?

2024-07-12 20:27 UTC, desertaxle commented on src/prefect/runtime/flow_run.py
> +def get_parent_deployment_id() -> Optional[UUID]:
```suggestion
def get_parent_deployment_id() -> Optional[str]:
```

2024-07-12 20:38 UTC, 50Bytes-dev commented
@desertaxle done

2024-07-12 20:53 UTC, desertaxle requested changes
Once the last couple of stray changes to the workflow are taken out and the unused import is removed, this will be ready to merge

2024-07-12 20:53 UTC, desertaxle commented on .github/workflows/prefect-client.yml
> -      - client/*
Looks like there are some changes in this file that still need to be reverted.

2024-07-12 20:53 UTC, desertaxle commented on src/prefect/runtime/flow_run.py
> +from uuid import UUID
This import is not longer needed.

2024-07-12 21:25 UTC, 50Bytes-dev commented
@desertaxle check it

2024-07-13 11:43 UTC, 50Bytes-dev commented
@desertaxle please review

2024-07-13 15:10 UTC, desertaxle approved these changes
Thanks!

2024-07-13 15:10 UTC, merged