Add support for instance/class/static methods
PrefectHQ/prefect pull request #13944
Opened 2024-06-11 21:33 UTC by jlowin

This PR adds support for decorating instance/class/static methods as @flows or @tasks.

Today, methods aren't supported because the `self` argument; you'll get an error like `ParameterBindError: Error binding parameters for function 'instance_method': missing a required argument: 'self'.
Function 'instance_method' has signature 'self' but received args: () and kwargs: [].`.

This is because the binding process of methods isn't being respected, and the function signature (used for validating parameters) demands an explicit `self` call arg that will never be supplied.

The solution (for both flows and tasks) has two parts:
1. Implement the descriptor protocol on `Flows` and `Tasks`. When an instance method is accessed, this method is called with the instance as its first argument. We use that to create and return a copy of the Flow object which has that instance bound to its own `fn` as a first argument.
2. Remove the instance argument from the bound Flow's signature. This ensures that parameter validation works (because no check for self is ever made).

2024-06-11 21:44 UTC, zzstoatzz commented
fyi: I was curious about `BaseModel` here, so I tried, and it gets mad because the resulting method is not annotated with a type
```python
In [1]: from pydantic import BaseModel

In [2]: from prefect import flow

In [3]: class Foo(BaseModel):
   ...:     x: int
   ...:     @flow
   ...:     def f(self):
   ...:         print(self.x)
   
PydanticUserError: A non-annotated attribute was detected: `f = <prefect.flows.Flow object at 0x106e84950>`. All model fields require a type annotation; if `f` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
```


here's how it can work
```python
def test_flow_supports_instance_methods_with_basemodel(self):
    class Foo(pydantic.BaseModel):
        model_config = pydantic.ConfigDict(ignored_types=(Flow,))
        x: int = 5

        @flow
        def instance_method(self):
            return self.x

    assert Foo().instance_method() == 5
    assert isinstance(Foo().instance_method, Flow)
```

2024-06-11 22:14 UTC, cicdw requested changes
Clever - can you add some tests to confirm that `self` is properly provided to task input cache policies? (or really any hook that engages with task inputs, could also be `result_storage_key`)

2024-06-12 02:11 UTC, jlowin commented
@cicdw's request demonstrated that the original approach did *not* satisfy Prefect's internal parameter machinery since it was too implicit. 

I've updated the PR to reflect a new, far simpler, approach. Instead of returning a bound instance from the descriptor method, we store the bound instance on `__prefect_self__` in a way that let's Prefect's parameter functions detect and restore it.

2024-06-13 19:30 UTC, cicdw approved these changes
Nice!

2024-06-13 20:12 UTC, merged