Adds `as_completed` utility for `PrefectFuture`
PrefectHQ/prefect pull request #14641
Opened 2024-07-16 20:00 UTC by jeanluciano

Adds a utility that yields completed futures. Closes #14241 

### Example
```python
        @task
        def sleep_task(seconds):
            sleep(seconds)
            return 42

        @flow
        def flow():
            futures = random_task.map(range(10))
            for future in as_completed(futures):
                print(future.result())
```

### Checklist

- [ x ] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
- [ x ] This pull request references any related issue by including "closes `<link to issue>`"
  
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ x ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ x ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ x ] If this pull request adds functions or classes, it includes helpful docstrings.

2024-07-16 20:43 UTC, zzstoatzz commented on src/prefect/futures.py
> +        fs: The sequence of Futures (possibly created by different Executors) to
```suggestion
        futures: The sequence of Futures (possibly created by different Executors) to
```

2024-07-16 20:43 UTC, zzstoatzz commented on src/prefect/futures.py
> +def as_completed(futures: List[PrefectFuture], timeout=None) -> Iterator[PrefectFuture]:
i'd double check my suggestion, but this looks like its a Generator function right?
```suggestion
def as_completed(futures: List[PrefectFuture], timeout: Optional[float] = None) -> Generator[PrefectFuture, None]:
```

2024-07-16 20:43 UTC, zzstoatzz commented on src/prefect/futures.py
> +    futures = set(futures)
this overshadows the `futures` input arg, can we call this `unique_futures` or something?

2024-07-16 21:54 UTC, desertaxle commented
I think this implementation will be good for now, but it looks like futures early in the list will block futures later in the list from being yielded when they are complete until the futures earlier in the list are finished. Could you see if an implementation that would allow the behavior of this utility to not be dependent on the ordering of the passed in futures? I think a callback structure on `PrefectFuture` might make that possible.

2024-07-23 01:07 UTC, cicdw requested changes
a few stray debug logs that I think need to be removed, and a question

2024-07-23 01:07 UTC, cicdw commented on src/prefect/futures.py
> +                logger.debug(f"{future.result()}")
```suggestion
```

2024-07-23 01:07 UTC, cicdw commented on src/prefect/futures.py
> +                    logger.debug(f"done: {future.result()}")
```suggestion
```

2024-07-23 01:07 UTC, cicdw commented on src/prefect/task_runs.py
> +            await from_async.wait_for_call_in_loop_thread(
we're trying to move away from using these utilities - is this one necessary?

2024-07-25 15:47 UTC, desertaxle commented
FYI, I think we'll want to support this for the Dask and Ray flavors of `PrefectFuture` also

2024-07-25 22:18 UTC, zzstoatzz reviewed
nice!

a couple nits and:

maybe we should add a test or two for cases where we throw exceptions / timeout? just to be explicit on what we expect

2024-07-25 22:18 UTC, zzstoatzz commented on src/prefect/futures.py
> +            """
nit: I think the ellipsis should be after the docstring here

2024-07-25 22:18 UTC, zzstoatzz commented on src/prefect/futures.py
> +    def add_done_callback(self, fn: Callable[[PrefectFuture], None]):
maybe we could have a docstring here to briefly explain the `call_with_self` business here?

2024-07-25 22:18 UTC, zzstoatzz commented on src/prefect/futures.py
> +) -> Generator[PrefectFuture, None]:
seems pretty elegant to me!

2024-07-25 22:28 UTC, cicdw requested changes
some small nitpicks about tests and duplicated code, the core implementation makes sense to me

2024-07-25 22:28 UTC, cicdw commented on src/integrations/prefect-dask/tests/test_task_runners.py
> +                for seconds in timings
I think this test would be more compelling if the timings were ordered in reverse, proving that `as_completed` actually affected the order that they yielded.
```suggestion
                for seconds in reversed(timings)
```

2024-07-25 22:28 UTC, cicdw commented on src/integrations/prefect-ray/tests/test_task_runners.py
> +            futures = [task_a.submit(seconds) for seconds in timings]
same comment as above
```suggestion
            futures = [task_a.submit(seconds) for seconds in reversed(timings)]
```

2024-07-25 22:28 UTC, cicdw commented on src/integrations/prefect-dask/prefect_dask/task_runners.py
> +    def add_done_callback(self, fn: Callable[[PrefectFuture], None]):
I don't think it's necessary to add these methods for each task runner given that `PrefectWrappedFuture` already has it implemented

2024-07-25 22:28 UTC, cicdw commented on src/prefect/task_runs.py
> +            instance._completion_events[task_run_id] = callback
this doesn't fit the typing on `instance._completion_events` - is this intentional?

2024-07-25 22:28 UTC, cicdw commented on tests/test_futures.py
> +        return super().add_done_callback(fn)
is this necessary or can you simply inherit this method?

2024-07-25 22:28 UTC, cicdw commented on tests/test_futures.py
> +            for i in timings:
```suggestion
            for i in reversed(timings):
```

2024-07-25 22:28 UTC, cicdw commented on tests/test_futures.py
> +        for i in timings:
```suggestion
        for i in reversed(timings):
```

2024-07-25 22:28 UTC, cicdw commented on tests/test_task_runners.py
> +    def add_done_callback(self, fn):
necessary?

2024-07-26 16:10 UTC, cicdw commented
Really weird that Ray is behaving strangely; @jeanluciano I don't think we need to optimize for a perfectly reversed output, as there is probably some latency in spinup that is allowing the 5 second sleep to execute faster.  Maybe just assert that `10` is the last one returned, which will prove that `as_completed` affected the return order (ultimately all we need for this specific test).

2024-07-26 16:11 UTC, cicdw commented
I would keep the Dask test as-is and only change the Ray test, between the two it's decent coverage

2024-07-26 18:29 UTC, jeanluciano commented
Yeah I thought it had to do with the way I was converting the object ref into a future, but setting the callback on the object ref directly behaves the same way.

2024-07-26 18:52 UTC, cicdw approved these changes

2024-07-26 18:59 UTC, merged