Flow run logs csv download
PrefectHQ/prefect pull request #14703
Opened 2024-07-22 19:19 UTC by pleek91

# Description
Adds a new endpoint `/api/flow_runs/{id}/logs` which downloads a csv of all logs a flow run created. This csv looks like
```
timestamp,level,flow_run_id,task_run_id,message
2024-07-22 17:58:14.037664+00:00,20,32ded098-2633-414e-90cf-242af9d6d2a8,,"Lorem ipsum http://google.com hello world https://example.com cache_key_fn, type: <class 'function'>, fn: <function task_input_hash at 0x7f165f8fba30>"
2024-07-22 17:58:15.039871+00:00,20,32ded098-2633-414e-90cf-242af9d6d2a8,,"Lorem ipsum http://google.com hello world https://example.com cache_key_fn, type: <class 'function'>, fn: <function task_input_hash at 0x7f165f8fba30>"
2024-07-22 17:58:16.080519+00:00,20,32ded098-2633-414e-90cf-242af9d6d2a8,,Finished in state Completed()

```

### Example
Going to `/api/flow_runs/{id}/logs` downloads a csv file to the browser.

### Checklist

- [ ] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

2024-07-22 19:28 UTC, cicdw requested changes
Totally understand the motivation here, and your implementation makes a lot of sense if it ran client-side.  However, `while True:` style loops like this have big performance implication (and risk) when run server side, and in addition this could eat up a lot of memory depending on the size of the logs being requested, so I think we're going to need to consider other alternatives.

@chrisguidry or @zangell44 let me know if you disagree with my take here

2024-07-22 19:32 UTC, chrisguidry commented
> Totally understand the motivation here, and your implementation makes a lot of sense if it ran client-side. However, `while True:` style loops like this have big performance implication (and risk) when run server side, and in addition this could eat up a lot of memory depending on the size of the logs being requested, so I think we're going to need to consider other alternatives.
> 
> @chrisguidry or @zangell44 let me know if you disagree with my take here

It looks like this is using a `StreamingResponse` with a generator, so it _should_ be okay from a memory perspective since it should only have a hard references to that 1000 logs at a time.

2024-07-22 19:41 UTC, chrisguidry reviewed
I _think_ we'll be good since you're using the `StreamingResponse`, but can we get a unit test in for this one?

2024-07-22 19:42 UTC, cicdw commented
Awesome, makes sense - deferring my review to @chrisguidry in that case 🫡

2024-07-22 19:44 UTC, pleek91 commented
@cicdw and @chrisguidry thank you! I'll work on some tests. Also @chrisguidry and @zangell44 curious about cloud and if this same solution would work there.

2024-07-22 19:46 UTC, chrisguidry commented
Yep I think streaming would work just fine on Prefect Cloud too, although there are a few more layers of load balancers/proxies involved.  When we get there, let's set aside some time to design a load test for it

2024-07-24 14:58 UTC, chrisguidry approved these changes
Looks great, thanks for that extra time on the testing!

2024-07-24 14:58 UTC, chrisguidry commented on tests/server/orchestration/api/test_flow_runs.py
> +            ]
There we go, nice!

2024-07-24 17:27 UTC, cicdw approved these changes

2024-07-25 13:29 UTC, discdiver approved these changes

2024-07-29 15:30 UTC, merged