Clearer presentation of unserializable parameters in the UI
PrefectHQ/prefect pull request #14921
Opened 2024-08-13 23:56 UTC by Andrew-S-Rosen

## Goal

When an unserializable parameter is provided to a flow run, a placeholder is stored in the UI. However, the current approach is very opaque, and this PR seeks to improve the user experience in this regard.

## Demonstration of the Problem

To demonstrate what I mean, let us consider an example. I have a dictionary provided as a parameter to a flow run that Prefect does not know how to serialize. In the "Parameters" tab of the UI, it shows the following:

```python
{
  "atoms": "<Atoms>"
}
```

In other words, the value here could not be serialized and was instead transformed to `"<Atoms>"`, which is the name of the class (i.e. `Atoms`). However, if instead of storing the name of the class we instead stored `str(value)`, we would have something potentially much more descriptive (depending on if there is a `__repr__` for the unserializable class). Indeed, in this case, we get

```python
{"atoms": "Atoms(symbols='Cu', pbc=True, cell=[[0.0, 1.805, 1.805], [1.805, 0.0, 1.805], [1.805, 1.805, 0.0]])"}`
```

This is much more informative for the end-user.

## This PR

In this PR, I have changed the output in the UI to display `str(value)` rather than the name of the object.

### Checklist

- [X] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [X] If this pull request adds new functionality, it includes unit tests that cover the changes
- [X] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [X] If this pull request adds functions or classes, it includes helpful docstrings.

2024-08-14 00:02 UTC, cicdw requested changes
Thank you for the contribution @Andrew-S-Rosen ! 

I have a concern with this implementation that we've run into in the past which is that this has no natural compression and runs the risk of attempting to send large payloads.  

As an example if `value = {"x": list(range(10000))}`.  I know that specific data type _is_ serializable but it's easy to construct other classes that don't have compressed string representations.  This is originally why we went with storing only the type in these edge cases.  Definitely open to other ideas but it would need to have an inherent size limit.

2024-08-14 00:05 UTC, Andrew-S-Rosen commented
@cicdw: Brilliant edge case! Yes, you are absolutely right. 

I don't think there is anything wrong with truncating the representation to a maximum length (with a `...` afterwards). I still think this would provide more insight than just the type. Alternatively, we could default to the type if `str(value)` is greater than some threshold if you don't like the idea of a truncated `str` representation. Thoughts?

2024-08-14 00:30 UTC, cicdw commented
The pedantic side of me worries that `str(value)[:N]` will still have client-side edge cases with performance in actually computing the string and I tend to avoid optimizing for display (instead focusing on optimizing for functionality). 

That being said, I'm probably overthinking this so I'm OK picking some reasonable value of `N` and seeing if we run into any issues.

2024-08-14 01:31 UTC, Andrew-S-Rosen commented
> The pedantic side of me worries that str(value)[:N] will still have client-side edge cases with performance in actually computing the string and I tend to avoid optimizing for display (instead focusing on optimizing for functionality).

This is certainly understandable. In practice, one could imagine a user passing a large dictionary with many key/value pairs, only some of which are not serializable but which collectively make the parameter not serializable as a whole. It might take a few seconds to string-ify it, in particularly extreme cases.

We _could_ do something like `sys.getsizeof()`. For instance,

```python
import sys
a=["s"]*100000000
sys.getsizeof(a) # outputs 800000056
```

to decide when to avoid string-ification, but this would be purely subjective. It also won't account for situations where a custom `__str__` method might not be implemented efficiently for a given object.

I'm going to leave this open for a short period and think on this for a little bit.

2024-08-15 04:11 UTC, zzstoatzz commented
for what it's worth, I'll leave this here if we end up fine with computing the string
```python
def _display_unserializable_value(value: Any) -> str:
    fallback = f"<{type(value).__name__}>"
    try:
        _str = str(value)
    except Exception:
        return fallback
    return truncated_to(50, _str) if _str else fallback # from prefect.utilities.text import truncated_to
```

which gives
```python
{
  "unserializable": "values=[0, 1, 2, 3, 4, 5,...4847 additional characters... 995, 996, 997, 998, 999]"
}
```

when you have something like
```python
class Unserializable(BaseModel):
    values: list[int] = list(range(1000))

    @model_serializer
    def serialize(self):
        raise TypeError("Cannot serialize")
```

2024-09-24 16:01 UTC, closed without merging