Add a deployment concurrency limit field
PrefectHQ/prefect pull request #14929
Opened 2024-08-14 14:50 UTC by jeanluciano

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

2024-08-14 20:46 UTC, bunchesofdonald approved these changes
Lookin' good!

2024-08-14 20:46 UTC, bunchesofdonald commented on src/prefect/client/schemas/objects.py
> +        default=..., description="The concurrency limit for the deployment."
Any reason not to default this to `None` ?

2024-08-14 20:46 UTC, bunchesofdonald commented on src/prefect/server/database/orm_models.py
> +    concurrency_limit = sa.Column(sa.Integer, default=None, nullable=True)
With sqlalchemy2 we can actually have correct typing by using `Mapped`:

```suggestion
    concurrency_limit: Mapped[int] = mapped_column(sa.Integer, default=None, nullable=True)
```

2024-08-15 03:53 UTC, zzstoatzz approved these changes
lgtm!

2024-08-15 03:53 UTC, zzstoatzz commented on src/prefect/server/database/migrations/versions/postgresql/2024_08_14_150111_97429116795e_add_deployment_concurrency_limit.py
> +    # ### commands auto generated by Alembic - please adjust! ###
nit:
```suggestion
```

2024-08-15 03:53 UTC, zzstoatzz commented on src/prefect/server/database/migrations/versions/postgresql/2024_08_14_150111_97429116795e_add_deployment_concurrency_limit.py
> +    # ### end Alembic commands ###
same

2024-08-15 03:53 UTC, zzstoatzz commented on src/prefect/server/database/migrations/versions/postgresql/2024_08_14_150111_97429116795e_add_deployment_concurrency_limit.py
> +    # ### end Alembic commands ###
same

2024-08-15 03:53 UTC, zzstoatzz commented on src/prefect/server/database/migrations/versions/sqlite/2024_08_14_145052_f93e1439f022_add_deployment_concurrency_limit.py
> +    # ### end Alembic commands ###
same

2024-08-15 03:53 UTC, zzstoatzz commented on src/prefect/server/database/migrations/versions/sqlite/2024_08_14_145052_f93e1439f022_add_deployment_concurrency_limit.py
> +    # ### end Alembic commands ###
same

2024-08-15 13:19 UTC, discdiver approved these changes
LGTM. Another PR to update the docs would be helpful for users. Maybe that's already on your radar?

2024-08-15 14:17 UTC, desertaxle requested changes
Can you add a test to ensure the default `concurrency_limit` shows up on responses from the API? That'll ensure the plumbing is all correctly in place!

2024-08-15 14:17 UTC, desertaxle commented on src/prefect/server/database/orm_models.py
> +    concurrency_limit: Mapped[int] = mapped_column(
nit
```suggestion
    concurrency_limit: Mapped[Union[int, None]] = mapped_column(
```

2024-08-15 15:51 UTC, desertaxle approved these changes

2024-08-15 16:22 UTC, merged