Flow code storage docs improvements
PrefectHQ/prefect pull request #15519
Opened 2024-09-27 17:15 UTC by discdiver

Creates  Python `deploy` and `prefect.yaml` examples and reorganizes the page for more clear and comprehensive examples of flow code storage.

Closes #14387

### Checklist

- [X] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

2024-10-01 16:01 UTC, zzstoatzz requested changes
I think these examples need to be consolidated and fixed

- we should define a variable for `source` for use in `from_source` so its easier to read
- I think we can make use of panes/tabs to make better use of space

2024-10-02 16:35 UTC, discdiver commented on docs/3.0/deploy/infrastructure-concepts/store-flow-code.mdx
> +    ```
yeah. I'm still making changes here. I'll re-request review when all made.

2024-10-07 19:22 UTC, zzstoatzz approved these changes
looks good to me!

i have 2 requests:
- there's some incorrect indenting that I've highlighted
- can we use descriptive names for the `source`? like `git_repo` for example, so it reads more intuitively

2024-10-07 19:22 UTC, zzstoatzz commented on docs/integrations/prefect-github/index.mdx
> +    source = GitRepository(
```suggestion
    git_repo = GitRepository(
```

2024-10-07 19:22 UTC, zzstoatzz commented on docs/integrations/prefect-github/index.mdx
> +    flow.from_source(source=source, entrypoint="my_file.py:my_flow").deploy(
```suggestion
    flow.from_source(source=git_repo, entrypoint="my_file.py:my_flow").deploy(
```

2024-10-07 19:23 UTC, zzstoatzz commented on docs/integrations/prefect-github/index.mdx
> +    source = GitRepository(
one example of what I mean

2024-10-07 19:26 UTC, discdiver commented on docs/integrations/prefect-github/index.mdx
> +    source = GitRepository(
Sure thing.

2024-10-07 19:26 UTC, discdiver commented on docs/3.0/deploy/infrastructure-concepts/store-flow-code.mdx
> +        )
Thought I got all those. Good catch.

2024-10-07 19:59 UTC, merged