fix wrong exception in lazy import __getattr__ (#15739)
PrefectHQ/prefect pull request #15741
Opened 2024-10-17 15:53 UTC by protagonyist

raise AttributeError instead of ModuleNotFoundError in __getattr__ in prefect/__init__.py (issue https://github.com/PrefectHQ/prefect/issues/15739) 
### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ ] If this pull request adds functions or classes, it includes helpful docstrings.

2024-10-17 15:54 UTC, protagonyist commented
closes https://github.com/PrefectHQ/prefect/issues/15739

2024-10-18 09:17 UTC, protagonyist commented
@desertaxle added test case to `tests/test_exceptions.py`

2024-10-18 17:37 UTC, zzstoatzz approved these changes
lgtm! one small nit on naming

thank you @protagonyist

2024-10-18 17:37 UTC, zzstoatzz commented on tests/test_exceptions.py
> +    def test_attributeerror_on_getattr(self):
```suggestion
    def test_attribute_error_on_getattr(self):
```

2024-10-18 17:49 UTC, zzstoatzz requested changes
oops! @desertaxle made a good point, which is that we should also have a case testing


```
from prefect import foo
```

2024-10-20 14:59 UTC, protagonyist commented
Fixed AttributeError test case name, added tests for `from prefect import foo` and `import prefect.foo`!

2024-10-21 16:06 UTC, desertaxle approved these changes
LGTM!

2024-10-21 16:18 UTC, merged