Add caching doc section on unserializable inputs
PrefectHQ/prefect pull request #16135
Opened 2024-11-27 17:48 UTC by zzstoatzz

2024-11-27 17:48 UTC, zzstoatzz commented on docs/v3/develop/big-data.mdx
> +Learn more about [caching](/v3/develop/task-caching/).
this pointed to the top of the tasks page, which does not discuss caching

2024-11-27 18:58 UTC, cicdw requested changes
This is great, my only suggestion is to include a sentence at the top that describes the common idea between both strategies; something like "the core idea is to adjust the serialization logic to only serialize certain properties of an input."

2024-11-27 19:07 UTC, zzstoatzz commented
> This is great, my only suggestion is to include a sentence at the top that describes the common idea between both strategies; something like "the core idea is to adjust the serialization logic to only serialize certain properties of an input."

good call! updated in [1ec84e9](https://github.com/PrefectHQ/prefect/pull/16135/commits/1ec84e916127f0e06f4a3a1a48a6f9f4c5553c58)

2024-11-27 22:35 UTC, cicdw approved these changes

2024-11-27 22:35 UTC, merged

2024-11-29 01:44 UTC, teocns commented
I think documentation could benefit from more concrete examples on how to use cache policy in real world scenarios
```
        cache_policy=(DEFAULT).configure(
            isolation_level=IsolationLevel.SERIALIZABLE,
            lock_manager=RedisLockManager(
                **{
                    k: v
                    for k, v in redis_block.as_connection_params().items()
                    if not k.startswith("_")
                },
            ),
            key_storage=redis_block,
        ),
        retries=0,
        retry_delay_seconds=1,
        timeout_seconds=timeout_seconds,
        log_prints=False,
        persist_result=True,
        result_serializer="json",
        cache_result_in_memory=True,
        cache_expiration=cache_expiration,
        result_storage=result_storage,
```

2024-11-29 01:46 UTC, zzstoatzz commented
> I think documentation could benefit from more concrete examples on how to use cache policy in real world scenarios

i agree @teocns! in the concept docs we try to keep things accessible but the guides would be a good place to put a concrete, real world example if you wanted to open a PR!