Bring ORM models and Alembic migrations in sync
PrefectHQ/prefect pull request #16221
Opened 2024-12-04 20:27 UTC by mjpieters

As I was looking into low-hanging fruit to improve prefect's type completeness, I ran into several issues with the ORM model definitions. Over time the migrations and the models have diverged somewhat, for various reasons, and this commit brings them back together again.

With this commit, you can run `prefect server database revision --autogenerate` in a clean checkout and alembic will generate empty migration steps. At the same time, the ORM models accurately reflect what is in the database.

The short version of what changed:

- Update the alembic `include_object` hook to support per-dialect filtering for indexes, and to avoid enum-to-varchar conversions for existing columns in SQLite.
- Add indexes added by manual migrations into their respective ORM models, with dialect-specific information where needed.
- Keep index names consistent across PostgreSQL and SQLite.
- Drop an index that was accidentally applied to the wrong table in the SQLite migrations.
- Drop an index that was created for a foreign key column now that it no longer is a foreign key.
- Correct ORM annotations for columns accidentally marked as nullable when they were converted to `Mapped[...]` / `mapped_column()`
- Mark `WorkPool.default_queue_id` as a foreign key in the ORM model; it already is one in the database.
- Drop columns that were removed from the ORM models.
- Use `Optional[...]` instead of `Union[..., None]` in annotations.

2024-12-04 20:28 UTC, mjpieters commented
This is a draft for now to get feedback, and to give me time to convert my notes into something a bit more readable for the long version.

2024-12-05 10:30 UTC, mjpieters commented
I'll be adding a new PR that builds on this one to move `orm_models.py` to be fully type annotated, using the SQLAlchemy 2.0 `Mapped[]` / `mapped_column()` style.

2024-12-05 15:31 UTC, desertaxle requested changes
This is fantastic! Thank you @mjpieters!

In addition to my comment about the dependency cycle warning raised by SQLAlchemy, I'm seeing a number of warnings when generating a migration against a SQLite DB:
```
/Users/alexander/dev/mjpieters/prefect/.venv/lib/python3.12/site-packages/alembic/ddl/impl.py:817: UserWarning: autogenerate skipping metadata-specified expression-based index 'ix_artifact__key_created_desc'; dialect 'sqlite' under SQLAlchemy 2.0.36 can't reflect these indexes so they can't be compared
  util.warn(
/Users/alexander/dev/mjpieters/prefect/.venv/lib/python3.12/site-packages/alembic/ddl/impl.py:817: UserWarning: autogenerate skipping metadata-specified expression-based index 'ix_flow_run__coalesce_start_time_expected_start_time_asc'; dialect 'sqlite' under SQLAlchemy 2.0.36 can't reflect these indexes so they can't be compared
  util.warn(
/Users/alexander/dev/mjpieters/prefect/.venv/lib/python3.12/site-packages/alembic/ddl/impl.py:817: UserWarning: autogenerate skipping metadata-specified expression-based index 'ix_flow_run__coalesce_start_time_expected_start_time_desc'; dialect 'sqlite' under SQLAlchemy 2.0.36 can't reflect these indexes so they can't be compared
  util.warn(
09:22:00.832 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('ix_flow_run__end_time_desc', <sqlalchemy.sql.elements.UnaryExpression object at 0x106f74650>). The dialect implementation should either skip expression indexes or provide a custom implementation.
09:22:00.832 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('ix_flow_run__expected_start_time_desc', <sqlalchemy.sql.elements.UnaryExpression object at 0x106f74530>). The dialect implementation should either skip expression indexes or provide a custom implementation.
09:22:00.833 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('ix_flow_run__next_scheduled_start_time_asc', <sqlalchemy.sql.elements.UnaryExpression object at 0x106f74ef0>). The dialect implementation should either skip expression indexes or provide a custom implementation.
09:22:00.836 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('uq_flow_run_state__flow_run_id_timestamp_desc', Column('flow_run_id', UUID(), ForeignKey('flow_run.id'), table=<flow_run_state>, nullable=False), <sqlalchemy.sql.elements.UnaryExpression object at 0x106ef1f10>, unique=True). The dialect implementation should either skip expression indexes or provide a custom implementation.
09:22:00.843 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('ix_task_run__end_time_desc', <sqlalchemy.sql.elements.UnaryExpression object at 0x1070200b0>). The dialect implementation should either skip expression indexes or provide a custom implementation.
09:22:00.844 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('ix_task_run__expected_start_time_desc', <sqlalchemy.sql.elements.UnaryExpression object at 0x106f77e60>). The dialect implementation should either skip expression indexes or provide a custom implementation.
09:22:00.844 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('ix_task_run__next_scheduled_start_time_asc', <sqlalchemy.sql.elements.UnaryExpression object at 0x106f77dd0>). The dialect implementation should either skip expression indexes or provide a custom implementation.
09:22:00.847 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('uq_task_run_state__task_run_id_timestamp_desc', Column('task_run_id', UUID(), ForeignKey('task_run.id'), table=<task_run_state>, nullable=False), <sqlalchemy.sql.elements.UnaryExpression object at 0x106ef3560>, unique=True). The dialect implementation should either skip expression indexes or provide a custom implementation.
09:22:00.847 | WARNING | alembic.ddl.impl - Generating approximate signature for index Index('ix_task_run_state_cache__cache_key_created_desc', Column('cache_key', String(), table=<task_run_state_cache>, nullable=False), <sqlalchemy.sql.elements.UnaryExpression object at 0x106f4a1b0>). The dialect implementation should either skip expression indexes or provide a custom implementation.
```
It looks like you added support for checking `ddl_if` in `src/prefect/server/database/_migrations/env.py`, so are these indexes that we should add `.ddl_if(dialect="postgresql")` to?

2024-12-05 15:31 UTC, desertaxle commented on src/prefect/server/database/orm_models.py
> +        UUID, sa.ForeignKey("work_queue.id", ondelete="RESTRICT"), nullable=True
When I generate a new migration from your branch I see this warning:
```
SAWarning: Cannot correctly sort tables; there are unresolvable cycles between tables
"work_pool, work_queue", which is usually caused by mutually dependent foreign ke
constraints.  Foreign key constraints involving these tables will not be considered;
this warning may raise an error in a future release.`
```
From the [SQLAlchemy docs](https://docs.sqlalchemy.org/en/20/core/constraints.html#creating-dropping-foreign-key-constraints-via-alter), it looks like we can resolve this using the `use_alter` kwarg to resolve the dependency cycle:
```suggestion
        UUID, sa.ForeignKey("work_queue.id", use_alter=True, ondelete="RESTRICT"), nullable=True
```

2024-12-05 16:20 UTC, mjpieters commented
> It looks like you added support for checking `ddl_if` in `src/prefect/server/database/_migrations/env.py`, so are these indexes that we should add `.ddl_if(dialect="postgresql")` to?

I think we'd have to then also define a `.ddl_if(dialect="sqlite")` version. I'll take a look.

2024-12-05 16:28 UTC, mjpieters commented
Right, the issue is the combination of strings and `sa.desc()`. I'm replacing these with `@declared_attr.directive` methods so the `Index()` objects can be created referencing the column instances; e.g.:

```python
    @declared_attr.directive
    def __table_args__(cls) -> Iterable[sa.Index]:
        return (
            sa.Index(
                "ix_artifact__key",
                cls.key,
            ),
            sa.Index(
                "ix_artifact__key_created_desc",
                cls.key,
                cls.created.desc(),
                postgresql_include=[
                    "id",
                    "updated",
                    "type",
                    "task_run_id",
                    "flow_run_id",
                ],
            ),
        )
```

2024-12-05 16:54 UTC, olearycrew commented
Thanks for these contributions @mjpieters !

2024-12-05 17:03 UTC, mjpieters commented
There are two `autogenerate skipping metadata-specified expression-based index` warnings left, and we can't avoid those. That's because these warnings are generated _before_ the `include_object()` hook is called and so we can't use `ddl_if()` to filter the indexes out.

The only alternative would be to not specify the indexes in the ORM models module, and then tell alembic to not drop these indexes when generating a migration. I think that would be worse off, as the indexes then just drop out of sight and people will forget to manage their migrations properly.

2024-12-05 17:49 UTC, mjpieters commented
I have no idea why the `tests/test_flows.py::TestFlowTimeouts::test_timeout_does_not_wait_for_completion_for_sync_flows` test failed in the CI pipeline; I can't reproduce that locally.

2024-12-05 18:13 UTC, desertaxle approved these changes
Amazing! Thank you!

2024-12-05 18:13 UTC, merged