Allow copying of directories into Docker image
PrefectHQ/prefect pull request #3299
Opened 2020-09-11 11:01 UTC by sevberg

## Summary
This will allow user to copy whole directories into the built docker image with only a single COPY command

## Changes
Docker's COPY command can accept a directory path just as easily as it can accept a file path, but shutil.copy2 (the function Prefect currently used to prepare the file to be copied) fails if given a path to a directory. Therefore a check has been added which first checks if the user specified path is a file and, if it is, shutil.copy2 is still used. On the other hand, if a directory path is provided then shutil.copytree is used.

## Importance
Aligns the capabilities of Docker's COPY command with Prefect's image build workflow

## Checklist

This PR:

- [x] adds new tests (if appropriate)
    - No suitable test to update
- [ ] adds a change file in the `changes/` directory (if appropriate)
    - TODO
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)
    - TODO

2020-09-12 18:48 UTC, cicdw requested changes
This is a great addition!  Two requested changes related to your change log entry edits.  Also if you could add a test that would be 💯

2020-09-12 18:48 UTC, cicdw commented on changes/pr3296.yaml
> -enhancement:
Looks like this file was accidentally deleted

2020-09-12 18:48 UTC, cicdw commented on changes/pr3299.yaml
> +  - "Allow copying of directories into Docker image - [#3299](https://github.com/PrefectHQ/prefect/pull/3299)"
You should add yourself as a contributor here!  To do so, include:

```
contributor:
  - "[Contributor Name](https://github.com/sevberg)"
```
at the bottom of this file

2020-09-17 16:14 UTC, sevberg commented
> This is a great addition! Two requested changes related to your change log entry edits. Also if you could add a test that would be 💯

Test is added! Where can I collect my 💯??  😋

2020-09-17 18:54 UTC, cicdw approved these changes
Thanks for the changes @sevberg - LGTM!

You can collect your 💯  by mentioning `@marvin-robot` on this PR and he'll enter you into a drawing for a free annual Cloud license 😜

2020-09-17 18:55 UTC, merged