Enhance the RunGreatExpectationsCheckpoint task
PrefectHQ/prefect pull request #3753
Opened 2020-12-02 19:27 UTC by joshmeek

## Summary
Enhances the `RunGreatExpectationsCheckpoint` task to allow for a lot more functionality! This also adds a call to the new artifacts API.

Example flow:

```python
from prefect import task, Flow, Parameter
from prefect.tasks.great_expectations import RunGreatExpectationsCheckpoint

checkpoint_task = RunGreatExpectationsCheckpoint()

@task
def get_batch_kwargs(datasource_name, dataset):
    dataset = ge.read_csv(dataset)
    return {"dataset": dataset, "datasource": datasource_name}

with Flow("ge_test") as flow:
    datasource_name = Parameter("datasource_name", default="data__dir")
    dataset = Parameter("dataset", default="data/yellow_tripdata_sample_2019-01.csv")
    batch_kwargs = get_batch_kwargs(datasource_name, dataset)

    expectation_suite_name = Parameter(
        "expectation_suite_name", default="yellow_tripdata_sample_2019-01.warning"
    )
    checkpoint_name = Parameter("checkpoint_name", default="action_list_operator")
    checkpoint_task(
        checkpoint_name=checkpoint_name,
        batch_kwargs=batch_kwargs,
        expectation_suite_name=expectation_suite_name,
    )

flow.register(project_name="Demo")
```

Screenshot of artifact in UI (click to zoom):

![image](https://user-images.githubusercontent.com/40716964/100921140-22ed6500-34aa-11eb-8345-90485e46e8cd.png)

## Changes
Adds a bunch of new kwargs to the task to allow for more in-memory great exepectations validations. Task signature now looks like the following:

```
        - checkpoint_name (str, optional): the name of the checkpoint; should match the filename of
            the checkpoint without .py
        - context (DataContext, optional): an in-memory GE DataContext object. e.g.
            `ge.data_context.DataContext()` If not provided then `context_root_dir` will be used to
            look for one.
        - assets_to_validate (list, optional): A list of assets to validate when running the
            validation operator. If not provided then `batch_kwargs` and `expectation_suite_name`
            will be used if context is provided. Also, if not provided and
            `get_checkpoint_from_context` is True then the assets will be loaded from that context.
        - batch_kwargs (dict, optional): a dictionary of batch kwargs to be used when validating
            assets.
        - expectation_suite_name (str, optional): the name of an expectation suite to be used when
            validating assets.
        - get_checkpoint_from_context (bool, optional): get the checkpoint from context. Defaults to
            `False`
        - context_root_dir (str, optional): the absolute or relative path to the directory holding
            your `great_expectations.yml`
        - runtime_environment (dict, optional): a dictionary of great expectation config key-value
            pairs to overwrite your config in `great_expectations.yml`
        - run_name (str, optional): the name of this  Great Expectation validation run; defaults to
            the task slug
        - run_info_at_end (bool, optional): add run info to the end of the artifact generated by this
            task. Defaults to `True`.
        - disable_markdown_artifact (bool, optional): toggle the posting of a markdown artifact from
            this tasks. Defaults to `False`.
```

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2020-12-02 19:38 UTC, madkinsz commented
Whoa sweet!

2020-12-02 19:50 UTC, madkinsz commented on src/prefect/tasks/great_expectations/checkpoints.py
> +        context: "DataContext" = None,  # noqa
Why noqa?

2020-12-02 19:50 UTC, madkinsz commented on src/prefect/tasks/great_expectations/checkpoints.py
> +            if get_checkpoint_from_context:
Can you add a comment to this if-else explaining the two different actions?

2020-12-02 19:51 UTC, madkinsz commented on src/prefect/tasks/great_expectations/checkpoints.py
> +        context: "DataContext" = None,  # noqa
Isn't this just `"ge.DataContext"` ?

2020-12-03 23:34 UTC, cicdw requested changes
I think we should use `signals.FAIL` instead of `VALIDATIONFAIL` (not a change you made in the PR, but it reminded me)

2020-12-03 23:34 UTC, cicdw commented on src/prefect/tasks/great_expectations/checkpoints.py
>              raise signals.VALIDATIONFAIL(result=results)
This is the only place we use this signal / state; I do remember the original motivation but now I'm inclined to think we should enter a standard `Failed` state instead

2020-12-04 16:37 UTC, cicdw approved these changes

2020-12-04 19:53 UTC, merged