Documented how to configure prefect server on a VM
PrefectHQ/prefect pull request #3830
Opened 2020-12-14 15:46 UTC by jackdesert

## Summary

Documented how to configure prefect server on a VM 

## Changes

Documentation

## Importance

Helpful for those running prefect server locally who develop in a virtual machine. 

## Checklist

Documentation changes only

2020-12-23 02:25 UTC, cicdw requested changes
LGTM!  I requested a few minor stylistic changes (no need to create links for the stand-in IP addresses)

2020-12-23 02:25 UTC, cicdw commented on docs/orchestration/server/deploy-local.md
> +configure the UI Endpoint Setting (aka apollo_url) just like you would in a server deploy.
```suggestion
configure the UI Endpoint Setting (aka `apollo_url`) just like you would in a server deploy.
```

2020-12-23 02:25 UTC, cicdw commented on docs/orchestration/server/deploy-local.md
> +[http://IP_OF_VIRTUAL_MACHINE:8080](http://IP_OF_VIRTUAL_MACHINE:8080),
```suggestion
`http://IP_OF_VIRTUAL_MACHINE:8080`,
```

2020-12-23 02:25 UTC, cicdw commented on docs/orchestration/server/deploy-local.md
> +[http://localhost:4200/graphql](http://localhost:4200/graphql).
```suggestion
`http://localhost:4200/graphql`
```

2020-12-23 02:25 UTC, cicdw commented on docs/orchestration/server/deploy-local.md
> +[http://IP_OF_VIRTUAL_MACHINE/graphql:4200](http://IP_OF_VIRTUAL_MACHINE/graphql:4200)
```suggestion
`http://IP_OF_VIRTUAL_MACHINE/graphql:4200`
```

2020-12-23 02:25 UTC, cicdw commented on docs/orchestration/server/deploy-local.md
> +(aka apollo_url) to point to
```suggestion
(aka `apollo_url`) to point to
```

2020-12-23 02:25 UTC, cicdw commented on docs/orchestration/server/deploy-local.md
> +(aka apollo_url) will work fine.
```suggestion
(aka `apollo_url`) will work fine. 
```

2021-08-24 22:05 UTC, madkinsz approved these changes

2021-11-30 19:48 UTC, tpdorsey approved these changes

2021-11-30 19:48 UTC, tpdorsey commented on docs/orchestration/server/deploy-local.md
> +You can set this directly from the browser. First click *Menu* -> *Home*. In the *Connecting your Infrastructure* block, select the *Prefect Server* tab. Then you'll see this configuration option und
```suggestion
You can set this directly from the browser. First click **Menu > Home**. In the **Connecting your Infrastructure** block, select the **Prefect Server** tab. Then you'll see this configuration option under **Connect the UI**: 
```

2021-11-30 19:48 UTC, tpdorsey commented on docs/orchestration/server/deploy-local.md
> +If you are running prefect server on a virtual machine, you may need to
```suggestion
If you are running prefect server on a virtual machine (VM), you may need to 
```

2021-11-30 19:48 UTC, tpdorsey commented on docs/orchestration/server/deploy-local.md
> +configure the UI Endpoint Setting (aka `apollo_url`) just like you would in a server deploy.
```suggestion
configure the UI Endpoint Setting (`apollo_url`) just like you would in a server deploy.
```

2021-11-30 19:48 UTC, tpdorsey commented on docs/orchestration/server/deploy-local.md
> +If you are running prefect server on a virtual machine, you may need to
```suggestion
If you are running Prefect server on a virtual machine, you may need to 
```

2021-11-30 19:48 UTC, tpdorsey commented on docs/orchestration/server/deploy-local.md
> +(aka `apollo_url`) to point to
```suggestion
(`apollo_url`) to point to
```

2021-11-30 19:48 UTC, tpdorsey commented on docs/orchestration/server/deploy-local.md
> +If you are a running prefect server inside a virtual machine using vagrant,
```suggestion
If you are a running Prefect server inside a VM using vagrant, 
```

2021-11-30 19:48 UTC, tpdorsey commented on docs/orchestration/server/deploy-local.md
> +(aka `apollo_url`) will work fine.
```suggestion
(`apollo_url`) will work fine. 
```

2021-11-30 19:48 UTC, tpdorsey commented on docs/orchestration/server/deploy-local.md
> +If you are a running prefect server inside a virtual machine using vagrant,
```suggestion
If you are a running prefect server inside a virtual machine using Vagrant, 
```

2021-11-30 19:49 UTC, tpdorsey commented
Looks good. Thank you!

2021-11-30 19:50 UTC, madkinsz approved these changes

2021-11-30 22:37 UTC, merged