New flow registration CLI
PrefectHQ/prefect pull request #4256
Opened 2021-03-16 18:37 UTC by jcrist

This PR deprecates the previous `prefect register flow` CLI in favor of a new `prefect register` CLI with lots more functionality.

Features:

- Allows registering multiple flows in a single call. Flows can be specified by `--path` (path to a file or directory containing flows) or by `--module` (an importable python module containing flows). Both options can be specified multiple times in a single call for more flexibility.
- A `--name` flag can be used to subselect flows to only register flows with a specific name (or names). If unspecified, all flows found are registered.
- By default, a flow will only be re-registered if it is *structurally different* than the existing version. This means that small edits to the source of tasks won't require re-registration, and the CLI will automatically detect this to avoid needlessly bumping the version. This can be disabled by passing in `--force`.
- A `--watch` flag for watching for changes in a directory/path/module, and re-registering flows on change. This can be used during development to automatically re-register your flows on save (as needed), or as part of a deployment for users who want to watch and auto-update flows from a specific directory (similar to airflow's DAG directory).

These features simplify auto-registering flows from within CI. For example, with github actions you might add the following step to your CI workflow to auto-register all flows in a `flows/` directory on merge.

```yaml
- name: Register Flows
  if: github.ref == 'refs/heads/master'
  run: prefect register flows --project testing --path flows
```

Fixes #4233.

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2021-03-16 18:37 UTC, jcrist commented
Demo:

![register-cli](https://user-images.githubusercontent.com/2783717/111362461-cc70f480-865c-11eb-801f-c2555ba74654.gif)

2021-03-19 02:38 UTC, cicdw requested changes
The most minor request to change a variable name - otherwise this LGTM, and it seems like you've thought through all the edge cases

2021-03-19 02:38 UTC, cicdw commented on src/prefect/cli/register.py
> +    if ctx.invoked_subcommand is not None:
Ah I see what you mean now

2021-03-19 03:21 UTC, jcrist commented on src/prefect/cli/register.py
> +    ns = {}
Sure, done.

2021-03-19 16:53 UTC, cicdw approved these changes

2021-03-19 16:55 UTC, merged