Remove forcerm=True from DockerStorage
PrefectHQ/prefect pull request #4584
Opened 2021-05-26 12:42 UTC by orf

## Summary

`forcerm=True` effectively disables the docker caching mechanism, which is quite useful when building images locally using `prefect register --watch`. With this change docker builds are now cached, massively reducing build and push times.

## Changes

Remove `forcerm=True` from the docker build command.

## Importance

Slow builds suck.

## Checklist

This PR:

- [x] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2021-05-26 14:45 UTC, orf commented
Appveyor fails with:

```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

🤔

2021-05-26 15:41 UTC, madkinsz commented
Hey @orf -- this makes sense to me although I'll have to talk to the team to see why we were doing that in the first place.

Feel free to ignore appveyor; I'm in the middle of replacing it with Github Actions (which confusingly did not run here?) https://github.com/PrefectHQ/prefect/pull/4567

2021-05-26 17:31 UTC, orf commented
Thank you! For context I'm evaluating Prefect, but right now a simple flow that uses DockerStorage takes ~5 minutes to build and push. With this change it's down to ~10 seconds which is ideal for rapid iteration.

An alternative (and better) fix is to use buildkit, but unfortunately the Python Docker library doesn't support this yet.

2021-05-26 18:10 UTC, madkinsz commented
That makes sense @orf -- I think the historical concern here is that your flow may not be copied into the image if it has changed but from what I understand about layer caching, the pickle blob should be different and invalidate the cache.

This all said, generally we recommend not using `DockerStorage` when you can get away with a file based storage like `GitHub` or `S3` and a `DockerRun` run config which tends to alleviate any slow build concerns.

2021-05-26 18:28 UTC, orf commented
We're still early on our Prefect journey, but it seemed that `DockerStorage` was a perfect mix as it allowed us to version our project dependencies alongside the exact flows. If we went with a separate storage (i.e Github + DockerRun) we'd need to wait for an external process to potentially build any changes to the docker image that's required to run the flow. Failure to do so would mean that the flow either launches with an old container (if you're using the `latest` tag) or that your flow can't start because the image hasn't built yet.

It also seemed perfect for local experimentation. But I'll keep your advice in mind and explore other options!

2021-05-26 19:17 UTC, madkinsz commented
> We're still early on our Prefect journey, but it seemed that `DockerStorage` was a perfect mix as it allowed us to version our project dependencies alongside the exact flows that run in them. If we went with a separate storage (i.e Github + DockerRun) we'd need to wait for an external process to potentially build any changes to the docker image that's required to run the flow. Failure to do so would mean that the flow either launches with an old container (if you're using the `latest` tag) or that your flow can't start because the image hasn't built yet.
> 
> It also seemed perfect for a local experimentation loop that can be trivially pushed to a k8s executor, and a simple way to segment production flows from experimental ones (different ECR repositories with different permissions).
> 
> But I'll keep your advice in mind and explore other options!

That makes sense! I'm curious where you'll land. You might find https://github.com/PrefectHQ/prefect/discussions/4042 interesting.

Regarding this PR, we're chatting about it internally and I think we'll have to give it a try to make sure it handles edge cases before accepting it.

2021-05-26 20:13 UTC, madkinsz requested changes
Can you add a changelog entry? https://github.com/PrefectHQ/prefect/tree/master/changes

2021-05-27 10:37 UTC, orf commented
Done!

2021-05-27 14:25 UTC, madkinsz approved these changes
Thanks! Looking forward to seeing you around more

2021-05-27 14:26 UTC, merged