Exposes scheduling activation from `prefect register` CLI
PrefectHQ/prefect pull request #4752
Opened 2021-07-09 14:37 UTC by gmontanola

## Summary
Enables toggling schedule activation upon CLI flow registering. Useful for CI and development

## Changes
1. New CLI option `--schedule/--no-schedule` for the `register` command. Defaults to `--schedule`.
2. This option is passed down util it reaches `register_serialized_flow` and adds a new `input` called `et_schedule_active` to GraphQL request.

## Importance
This will help with some CI use cases.

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2021-07-09 15:19 UTC, gmontanola commented
Hi there folks!

I'm not sure of how to implement tests for this feature. If someone happens to know a nice way, feel free to share it here!

2021-07-12 15:47 UTC, madkinsz requested changes
Thanks for doing this! Been on my list for a bit now.

There should be two tests for this, I think:

- One test where `prefect register` is called with `--schedule` and `--no-schedule` and the `Client` is mocked. Assert that `Client.register_serialized_flow` is called with the correct `set_schedule_active` value
- One test where `Client.graphql` is mocked and `Client.register_serialized_flow` is called with each value for `set_schedule_active`. Assert that `Client.graphql` is called with the correct flag value.

2021-07-12 15:47 UTC, madkinsz commented on src/prefect/cli/build_register.py
> +    schedule: bool = True,
I would prefer this be `set_schedule_active` for clarity

2021-07-12 15:47 UTC, madkinsz commented on src/prefect/cli/build_register.py
> +    schedule: bool = True,
In the `register` CLI code just `schedule` is fine

2021-07-12 15:47 UTC, madkinsz commented on src/prefect/cli/build_register.py
> +\b  Register a flow found in `flow.py` and disables its schedule.
```suggestion
\b  Register a flow found in `flow.py` and disable its schedule.
```

2021-07-12 15:47 UTC, madkinsz commented on src/prefect/cli/build_register.py
> +        "behavior is activated. Useful for CI and development."
```suggestion
        "Toggles the flow schedule upon registering. By default, the "
        "flow's schedule will be activated and future runs will be created. "
        "If disabled, the schedule will still be attached to the flow but "
        "no runs will be created until it is activated."
```

2021-07-12 16:19 UTC, madkinsz commented on src/prefect/cli/build_register.py
> +    schedule: bool = True,
Disregard, I forgot this was specific to `build_register`

2021-07-12 16:20 UTC, madkinsz commented
@gmontanola Whoops, I forgot that Jim created a non-Client method to register the flow. I'll edit my comment above to reflect the correct tests to add.

2021-07-20 18:56 UTC, merged