Adds dbt artifact URLs to DbtCloudRunJob
PrefectHQ/prefect pull request #5135
Opened 2021-11-11 14:29 UTC by desertaxle

## Summary

Adds the creation of link artifacts to capture the dbt Cloud job run artifacts in the Prefect Cloud console and also includes the links to dbt artifacts in the return value of the run method in the DbtCloudRunJob task.

## Changes

Adds artifacts and adds a key to the existing return type. Also updates exceptions raised in dbt cloud utils.

## Importance

Increases the discoverability and usability of dbt Cloud artifacts from job runs.

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [x] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2021-11-16 20:28 UTC, sungchun12 commented
Happy to test this in the wild before it's merged!

2021-11-17 18:18 UTC, desertaxle commented
Thanks @sungchun12! Do you have a sample dbt Cloud job that we could call from a Prefect flow?

2021-11-18 11:50 UTC, anna-geller commented
@desertaxle just tested it - it works fine, but the artifacts didn't show up:
![image](https://user-images.githubusercontent.com/86264395/142407009-886b7a84-c339-47ba-9efd-de47c3bd5ff0.png)

However, after changing `(create_link_artifact(link=link) for link in artifact_links)` to `create_link_artifact(link=artifact_links[1])` in the next flow run, it works fine:
![image](https://user-images.githubusercontent.com/86264395/142407153-047ee370-578f-49e5-981f-06f1498d0ad0.png)

Basically, prefect.backend.artifacts.create_link_artifact allows to only show one URL, but if we want to show multiple links in the artifact, then markdown artifact will probably work better:
```python
        if wait_for_job_run_completion:

            artifact_links = create_run_artifact_links(
                account_id=account_id, run_id=run["id"]
            )
           markdown = ""

            for url in artifact_links:
                markdown += f"- {url} \n"
            
            create_markdown_artifact(markdown)
```
Here is how it looked like in the flow run:
![image](https://user-images.githubusercontent.com/86264395/142410222-be8aff8c-a5a1-4d0a-8f88-8d838c6432da.png)

2021-11-18 13:27 UTC, desertaxle commented
@anna-geller Thanks for testing! That's a good call on generating a markdown artifact to hold multiple links. One question before I make that change, are you able to see the artifacts in your browser when you click on those links?

2021-11-18 13:56 UTC, sungchun12 commented
@desertaxle I do have an example dbt Cloud job. Are you suggesting I test it like Anna above or did you want permission access to invoke the job from prefect during your testing?

2021-11-18 15:23 UTC, anna-geller commented
> @anna-geller Thanks for testing! That's a good call on generating a markdown artifact to hold multiple links. One question before I make that change, are you able to see the artifacts in your browser when you click on those links?

@desertaxle I can open all of those URLs just fine in my browser, or save the files to my laptop: 
![image](https://user-images.githubusercontent.com/86264395/142444118-7b0cf50f-64c1-4a98-91cb-034b81abc837.png)
![image](https://user-images.githubusercontent.com/86264395/142444163-0381dc05-ed87-46fe-a973-12ee4db394d1.png)

2021-11-18 16:14 UTC, anna-geller commented
@desertaxle actually, the last link is always empty - is it because I haven't used any catalog in my dbt models? not sure what this catalog file is about but it's always empty for me, perhaps it can be skipped for the sake of artifact?
![image](https://user-images.githubusercontent.com/86264395/142453245-13bc1f26-09c4-4afb-9955-5768ce8a4364.png)

2021-11-18 16:39 UTC, desertaxle commented
> @desertaxle actually, the last link is always empty - is it because I haven't used any catalog in my dbt models? not sure what this catalog file is about but it's always empty for me, perhaps it can be skipped for the sake of artifact? ![image](https://user-images.githubusercontent.com/86264395/142453245-13bc1f26-09c4-4afb-9955-5768ce8a4364.png)

@sungchun12 Do you know why we wouldn't have a `catalog.json` artifact from a dbt Cloud job run? Is there a way to determine if a `catalog.json` was generated before we create the Prefect artifact?

2021-11-18 16:50 UTC, anna-geller commented
> > @desertaxle actually, the last link is always empty - is it because I haven't used any catalog in my dbt models? not sure what this catalog file is about but it's always empty for me, perhaps it can be skipped for the sake of artifact? ![image](https://user-images.githubusercontent.com/86264395/142453245-13bc1f26-09c4-4afb-9955-5768ce8a4364.png)
> 
> @sungchun12 Do you know why we wouldn't have a `catalog.json` artifact from a dbt Cloud job run? Is there a way to determine if a `catalog.json` was generated before we create the Prefect artifact?

@desertaxle good question, it looks like it's populated when someone uses the "dbt docs generate" command - let me try to add that command and see if file gets populated https://docs.getdbt.com/reference/artifacts/catalog-json

2021-11-18 17:11 UTC, anna-geller commented
@desertaxle ok, confirmed. When adding "dbt docs generate", this file is no longer empty, so we need to render all three URLs and we can perhaps explain in the docstring that this will generate 3 links and clarify which dbt command each link represents:
![image](https://user-images.githubusercontent.com/86264395/142463407-9281c734-0b34-4fb2-bf1f-23f42a6040b7.png)

2021-11-18 17:29 UTC, sungchun12 commented
@desertaxle @anna-geller I confirm that you need to run `dbt docs generate` to populate the `catalog.json`
![image](https://user-images.githubusercontent.com/19176976/142466072-09e43c9e-75f6-4661-abb6-fa0744dfcab8.png)


The same applies for `sources.json` requiring `dbt source freshness` in my earlier recommendation to add that as an artifact.

I recommend that the prefect task dynamically surfaces the artifacts if they exist in the dbt cloud job run.

2021-11-18 19:42 UTC, desertaxle commented
@sungchun12 I made a change to pull all the dbt artifacts via the [list artifacts endpoint](https://docs.getdbt.com/dbt-cloud/api-v2#operation/listArtifactsByRunId) so the artifacts will be dynamic based on the run. @anna-geller if that looks good in the Prefect UI then I think this should be good for full review.

2021-11-19 17:33 UTC, anna-geller commented
Something went wrong in the last commit:
![image](https://user-images.githubusercontent.com/86264395/142665893-cabf21fd-75e3-4d33-af6f-7836a6c6c0bb.png)
dbt_cloud_utils.py, line 188, in list_run_artifact_links - seems to return None?

2021-11-19 18:18 UTC, anna-geller commented
@desertaxle 

I made a tiny change and this works:
```python
        run = trigger_job_run(
            account_id=account_id,
            job_id=job_id,
            cause=cause,
            additional_args=additional_args,
            token=token,
        )
        if wait_for_job_run_completion:

            artifact_links = []
            try:
                job_run_result = wait_for_job_run(
                    account_id=account_id,
                    run_id=run["id"],
                    token=token,
                    max_wait_time=max_wait_time,
                )
                artifact_links = list_run_artifact_links(
                    account_id=account_id, run_id=run["id"], token=token
                )

                markdown = f"Artifacts for dbt Cloud run {run['id']} of job {job_id}\n"
                for link, name in artifact_links:
                    markdown += f"- [{name}]({link})\n"
                from prefect.backend.artifacts import create_markdown_artifact
                create_markdown_artifact(markdown)
            except DbtCloudListArtifactsFailed as err:
                self.logger.warn(
                    f"Unable to retrieve artifacts generated by dbt Cloud job run: {err}"
                )

            job_run_result["artifact_urls"] = [link for link, _ in artifact_links]

            return job_run_result

        else:
            return run
```

![image](https://user-images.githubusercontent.com/86264395/142671914-f6398a1e-26e6-48a1-b061-8e4d5530659c.png)

2021-11-19 19:37 UTC, anna-geller commented on src/prefect/tasks/dbt/dbt.py
@desertaxle you still need to actually call the create_markdown_artifact method:
```python
                markdown = f"Artifacts for dbt Cloud run {run['id']} of job {job_id}\n"
                for link, name in artifact_links:
                    markdown += f"- [{name}]({link})\n"
                from prefect.backend.artifacts import create_markdown_artifact
                create_markdown_artifact(markdown)
```

2021-11-22 17:14 UTC, madkinsz requested changes
Some minor changes

Otherwise, LGTM!

2021-11-22 17:14 UTC, madkinsz commented on changes/pr5135.yaml
> +  - "Adds artifacts to DbtCloudRunJob task - [#5135](https://github.com/PrefectHQ/prefect/pull/5135)"
```suggestion
  - "Add artifact publishing to `DbtCloudRunJob` task - [#5135](https://github.com/PrefectHQ/prefect/pull/5135)"
```

2021-11-22 17:14 UTC, madkinsz commented on src/prefect/tasks/dbt/dbt_cloud_utils.py
> +    """Base excpetion for all dbt Cloud Excpetions"""
```suggestion
    """Base exception for all dbt Cloud errors"""
```

2021-11-23 19:47 UTC, madkinsz approved these changes

2021-11-23 19:47 UTC, merged