Dbt cloud enterprise
PrefectHQ/prefect pull request #5273
Opened 2021-12-22 21:06 UTC by radbrt

## Summary
Add argument for custom domain to dbt Cloud task, letting Enterprise customers use the task. Enterprise customers have a custom subdomain like "cloud.corp.getdbt.com".

## Changes
Add a single argument, "domain", to the dbt.DbtCloudRunJob class init and run methods. The argument is optional and defaults to "cloud.getdbt.com".

## Importance
This will let enterprise customers of dbt Cloud use the dbt Cloud task.

## Checklist

This PR:

- [Y] adds new tests (if appropriate)
- [TODO] adds a change file in the `changes/` directory (if appropriate)
- [Y] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2021-12-27 16:29 UTC, desertaxle requested changes
Thanks for your contribution! This looking good! I requested a few small tweaks. After those are addressed this will be good to go!

2021-12-27 16:29 UTC, desertaxle commented on src/prefect/tasks/dbt/dbt.py
> +        domain: str = None,
I recommend setting the default value of this parameter to `cloud.getdbt.com` like so:
```suggestion
        domain: str = "cloud.getdbt.com",
```

2021-12-27 16:29 UTC, desertaxle commented on src/prefect/tasks/dbt/dbt.py
> +        - domain (str, optional): Custom domain for API call.
```suggestion
        - domain (str, optional): Custom domain for API call. Defaults to `cloud.getdbt.com`.
```

2021-12-27 16:29 UTC, desertaxle commented on src/prefect/tasks/dbt/dbt.py
> +            - domain (str, optional): Custom domain for API call.
```suggestion
        - domain (str, optional): Custom domain for API call. Defaults to `cloud.getdbt.com`.
```

2021-12-27 16:29 UTC, desertaxle commented on src/prefect/tasks/dbt/dbt_cloud_utils.py
> +        - domain (str): The domain the function should call, normally cloud.getdbt.com
```suggestion
        - domain (str): The domain the function should call (e.g. `cloud.getdbt.com`).
```

2021-12-27 16:29 UTC, desertaxle commented on src/prefect/tasks/dbt/dbt_cloud_utils.py
> +        - domain (str): The domain the function should call, normally cloud.getdbt.com
```suggestion
        - domain (str): The domain the function should call (e.g. `cloud.getdbt.com`).
```

2021-12-27 16:29 UTC, desertaxle commented on src/prefect/tasks/dbt/dbt_cloud_utils.py
> +        - domain (str): the domain the function should call, default cloud.getdbt.com
```suggestion
        - domain (str): The domain the function should call (e.g. `cloud.getdbt.com`).
```

2021-12-29 16:36 UTC, desertaxle approved these changes

2021-12-29 16:51 UTC, madkinsz commented
Thanks for contributing!

2021-12-29 16:51 UTC, merged