Add delay to create_flow_run
PrefectHQ/prefect pull request #5303
Opened 2022-01-07 16:52 UTC by cjmartian

## Summary

Allow for delays to be added to `create_flow_run()` as requested in https://github.com/PrefectHQ/prefect/issues/5171

## Changes

Adds an optional parameter to `create_flow_run()` - `schedule_delay_seconds: int` that delays `scheduled_start_time` by some amount of seconds.

## Importance

Requested by the community in [slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1637778182289200).

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [X] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2022-01-07 17:20 UTC, madkinsz commented
Hi! Thanks for contributing. As with the other open contribution for this, I don't think this needs to be a separate argument — see https://github.com/PrefectHQ/prefect/pull/5258#issuecomment-999721529

Let me know if you have any questions.

2022-01-10 05:01 UTC, cjmartian commented
Ah! Didn't realize there was a PR already open. 

What you're saying makes sense though. I'll look to reimplement that if the other PR doesn't before me.

2022-01-11 18:18 UTC, madkinsz commented on src/prefect/tasks/prefect/flow_run.py
> +    ):
Looks like tests are failing because `pendulum.duration` is a function and you want `Duration`.

2022-01-11 18:51 UTC, cjmartian commented on src/prefect/tasks/prefect/flow_run.py
> +    ):
Yeah I was trying to get `pendulum.duration.Duration`, thanks for that.

2022-01-11 21:34 UTC, madkinsz requested changes
This looks great to me, but I'd like a test covering the new behavior. Generally, it's easiest to mock `pendulum.now` and the client and assert the client is called with `now + delta`.

2022-01-12 17:26 UTC, madkinsz approved these changes
Thanks!

2022-01-12 17:26 UTC, merged