Fix response key in airbyte task health check
PrefectHQ/prefect pull request #5314
Opened 2022-01-11 13:40 UTC by mcfuhrt

## Summary
Currently an exception is thrown within the health check function when trying to trigger a connection in Airbyte.

## Changes
The non-existing key from the response used for the health check is replaced by a valid, existing key.

## Importance
Without the change it is not possible to execute an AirbyteTask successfully, because this will always lead to a KeyError: 'db'.

## Checklist
<img width="1459" alt="Bildschirmfoto 2022-01-11 um 14 40 34" src="https://user-images.githubusercontent.com/39857259/148953225-a26c73fb-3af9-46b7-9520-74ff8b83dcd0.png">

This PR:

- [x] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2022-01-11 17:54 UTC, desertaxle requested changes
Thanks for your contribution! It looks like this was a change that Airbyte made recently (in v0.35.4-alpha according to their [release notes](https://github.com/airbytehq/airbyte/releases)). Since we most likely will have users running older version of Airbyte where the health check contains the `db` key, I propose that we check for the presence of both the `db` flag and the `available` key to account for different Airbyte server versions. I think it will be a quick change, but let me know if you have any questions!

2022-01-12 07:48 UTC, mcfuhrt commented
> Thanks for your contribution! It looks like Airbyte recently made a change to their health check endpoint(in v0.35.4-alpha according to their [release notes](https://github.com/airbytehq/airbyte/releases)). Since we most likely will have users running older version of Airbyte where the health check contains the `db` key, I propose that we check for the presence of both the `db` flag and the `available` key to account for different Airbyte server versions. I think it will be a quick change, but let me know if you have any questions!

I have also thought about this and would consider it a good idea if both are offered. I have adjusted the PR accordingly

2022-01-12 14:48 UTC, desertaxle submitted a review, later dismissed
LGTM!

2022-01-12 15:45 UTC, madkinsz commented on src/prefect/tasks/airbyte/airbyte.py
> +                key = "available"
Preference for the more "pythonic" variable assignment here

```suggestion
            key = "available" if "available" in response.json() else "db"
```

2022-01-12 16:13 UTC, madkinsz approved these changes
Nice!

2022-01-12 16:13 UTC, merged