Verify GCP Task Library
PrefectHQ/prefect pull request #5618
Opened 2022-03-30 14:43 UTC by ahuang11

Consolidates
https://github.com/PrefectHQ/prefect/pull/5614
https://github.com/PrefectHQ/prefect/pull/5607
https://github.com/PrefectHQ/prefect/pull/5603

2022-03-30 15:32 UTC, desertaxle requested changes
Thanks for consolidating these PRs! Code changes look good. One comment on the changes file and can you also make the changes to the docs so that the GCS tasks have the verified badge?

2022-03-31 15:54 UTC, desertaxle requested changes
Realized when fixing the Census display issue that we need to close the Badge tag here also.

2022-03-31 15:54 UTC, desertaxle commented on docs/core/task_library/overview.md
> +    <td><Badge text="Verified" type="success"><img src="/logos/google_cloud.png" height="128" width="128" style="max-height: 128px; max-width: 128px;"><a href="https://docs.prefect.io/api/latest/task
```suggestion
    <td><Badge text="Verified" type="success"></Badge><img src="/logos/google_cloud.png" height="128" width="128" style="max-height: 128px; max-width: 128px;"><a href="https://docs.prefect.io/api/latest/tasks/gcp.html">Google Cloud</a></td>
```

2022-03-31 16:59 UTC, tpdorsey approved these changes

2022-03-31 18:03 UTC, desertaxle approved these changes

2022-04-04 15:55 UTC, ahuang11 commented
The tests passed, but GitHub isn't receiving the results.

2022-04-04 16:14 UTC, merged