add policy_id to NewCluster
PrefectHQ/prefect pull request #5681
Opened 2022-04-14 15:13 UTC by lababidi

## Summary

Added an additional missing Parameter from the Databricks API for policy_id

## Changes

## Importance

adding a policy id is critical to Databricks tasks

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2022-04-14 15:45 UTC, desertaxle commented
Thanks for the contribution @lababidi! Would you be able to add an entry to the change log in the `changes/` folder?

2022-04-14 16:20 UTC, lababidi commented
@desertaxle wanted to flag your attention for this simple PR, please :)

2022-04-14 19:38 UTC, desertaxle requested changes
One small comment on the changes file. Once that is address this should be good to go!

2022-04-14 19:38 UTC, desertaxle commented on changes/pr0000.yaml
> +  - "Added correct Databricks API params (autoscale, policy_id) - [Databricks API](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate)"
These file will be used to populate the release notes for the next release. We like to include links to the PR that made the change so I've made a suggestion to include the link to this PR and tweak the working. Also, the name of this file should be `pr5681.yaml`.
```suggestion
  - "Corrected Databricks new cluster API params: autoscale and policy_id - [#5681](https://github.com/PrefectHQ/prefect/pull/5681)"
```

2022-04-15 14:47 UTC, lababidi commented
@desertaxle changes file should be good to go! Thank you!

2022-04-18 21:05 UTC, lababidi commented
@desertaxle anything else you need?

2022-04-19 14:16 UTC, desertaxle approved these changes

2022-04-22 16:57 UTC, merged