Docs: Testing tasks as well as flows
PrefectHQ/prefect pull request #5697
Opened 2022-04-20 21:35 UTC by dannysepler

## Summary
Following up from [this slack thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1650416317687919), this should explain how to unit test tasks, in addition to flows.

Open question: should I explain more why someone may want to use `.fn()`, or is it pretty clear?

## Changes
Adds a bit more to the Testing section.

## Importance
To help folks know the options for their unit tests. It took me a while to realize that you didn't need a `flow` for unit tests. They were adding some runtime to our test suite, when the functions themselves were pretty simple!

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2022-04-22 18:50 UTC, desertaxle requested changes
I have one nit, but overall this looks great!

2022-04-22 18:51 UTC, desertaxle commented on docs/tutorials/testing.md
> +    state = my_flow().result()
Nit: Naming this variable `task_state` disambiguates with state `my_flow().result()` is returning.
```suggestion
    task_state = my_flow().result()
```

2022-04-26 14:17 UTC, desertaxle approved these changes
LGTM!

2022-04-26 14:24 UTC, tpdorsey approved these changes
Looks good. Thank you!

2022-04-26 14:36 UTC, merged