feat: allow to the endpoint url to boto3
PrefectHQ/prefect pull request #5729
Opened 2022-04-29 07:44 UTC by pmdroid

## Summary
This allow to use S3 compatible storage like minio or Scaleway.

## Changes
We added the optional parameter endpoint_url for creating S3 storage.

## Importance
This allows any S3 compatible object storage to be used (not just AWS).

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)
- [X] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

2022-05-03 15:45 UTC, desertaxle requested changes
Thanks for your contribution! This is a very useful addition! I had a suggestion for the documentation, but feel free to refine further if you think it's necessary.

2022-05-04 09:09 UTC, pmdroid commented
@desertaxle Hey thanks for checking, unfortunately i cannot see your suggested changes :(

2022-05-04 14:28 UTC, desertaxle commented on docs/concepts/storage.md
> +Usually the endpoint url looks something like this ```https://bucketname.s3.nl-ams.scw.cloud```.
```suggestion
### S3 Endpoint URL
When using an S3 compatible storage solution, like minio or Scaleway, or a VPC endpoint for S3, specify the endpoint URL when setting up storage via the CLI. An endpoint URL is not necessary when using AWS S3 directly.
```

2022-05-04 14:29 UTC, desertaxle commented
> unfortunately i cannot see your suggested changes :(
I guess it didn't go through before. You should be able to see it now!

2022-05-04 14:37 UTC, pmdroid commented
@desertaxle thanks for the changes  👍

2022-07-19 10:15 UTC, xyxz-web commented
would be great if this could be implemented soon, e.g. the only non-local storage I can access in my company is a custom (internal) S3 endpoint.

2022-07-19 10:19 UTC, xyxz-web commented
> May I suggest to also add a key_prefix to avoid storage at the "root" of a bucket. This involves two changes in storage.py in addition to adding the function arguments:
> 
> s3_client.upload_fileobj(Fileobj=stream, Bucket=self.bucket, Key=self.key_prefix +"/" + key) s3_client.download_fileobj(Bucket=self.bucket, Key=self.key_prefix +"/" + key, Fileobj=stream)

This is a great suggestion, but is this related to the endpoint url in any way?

2022-07-19 14:53 UTC, madkinsz commented
Hi! While this is still relevant for the `prefect-aws` package, we're removing the `S3Storage` object from the core library very soon.

I'd suggest using the `RemoteFileSystem` instead https://orion-docs.prefect.io/concepts/filesystems/#remote-file-system

We're including examples for using MinIO in the next release.

2022-08-23 20:56 UTC, madkinsz commented
I believe this has been resolved.

2022-08-23 20:56 UTC, closed without merging

2023-08-29 17:27 UTC, AyrtonDare commented
Hi @zanieb do you have any MinIO examples? 

prefect-aws always seems to refer to S3 regardless of the endpoint_url provided and there seems to be no way to use minio in the PrefectHQ docs