Add v1 label to 1.x prs
PrefectHQ/prefect pull request #6138
Opened 2022-07-30 00:40 UTC by jlowin

### Summary
This action should automatically apply the existing `v1` label to any PR's targeting the `1.x` branch

(I tried proving this out in #6137 by changing the base branch to 1.x but the total lack of shared history terrified github and it forcibly closed the PR)

2022-07-30 17:43 UTC, cicdw requested changes
I believe that some updated config is all that's needed here to achieve the same outcome

2022-07-30 17:43 UTC, cicdw commented on .github/pr-labeler.yml
> +'v1': ['1.x']
you shouldn't need these new files - we already have a labeler action, so I think appending this to https://github.com/PrefectHQ/prefect/blob/main/.github/labeler.yml will do the trick 👍

2022-08-02 00:52 UTC, jlowin commented
Oh that's a great idea -- ok I'll combine both of your suggestions

2022-08-02 00:52 UTC, jlowin commented
GitHub freaks out if you change the base branch to 1.x so going to reopen a new PR

2022-08-02 00:52 UTC, closed without merging