Prevent redundant transitions
PrefectHQ/prefect pull request #6852
Opened 2022-09-15 21:47 UTC by anticorrelator

Here we add a simple orchestration rule preventing redundant transitions. Among other things, this will prevent multiple Agents from orchestrating an active run in competing and inconsistent ways.

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a `fix`, `feature`, `enhancement`, `docs`, `collections`, or `maintenance` label categorizing the change.

2022-09-15 21:59 UTC, jlowin requested changes
Great stuff @anticorrelator and a win for the policy design to see how compact it is!

I don't think it's critical but I'd love to see an API-level unit test that proves this from a user's point of view (rather than the engine's point of view) by calling `set_flow_run_state(RUNNING)` twice in a row.

2022-09-15 21:59 UTC, jlowin commented on src/prefect/orion/orchestration/core_policy.py
> +                reason=f"This run cannot to the {proposed_state.type} state."
I think a word is missing here - "transition"?

2022-09-15 21:59 UTC, jlowin commented on src/prefect/orion/orchestration/core_policy.py
> +    STATE_PROGRESS = {
This is really neat

2022-09-15 21:59 UTC, jlowin commented on src/prefect/orion/orchestration/core_policy.py
> +            PreventBackwardsTransitions,
Where is this class? Maybe a rename?

2022-09-15 22:02 UTC, anticorrelator commented on src/prefect/orion/orchestration/core_policy.py
> +            PreventBackwardsTransitions,
oops! yes, this was a rename

2022-09-15 22:19 UTC, madkinsz commented
Just wondering, should we use REJECT and provide the current state allowing the client to decide if it should retry or give up? Or is this always going to be a case where the run is already being handled elsewhere and consequently we should force an ABORT?

2022-09-15 22:25 UTC, anticorrelator commented
I believe that if these transitions should never be allowed, the only reason why a client might attempt them is if we're in a bad state; I prefer aborting here instead of trying to solve for the cases where we might be able to recover

2022-09-16 05:02 UTC, madkinsz commented on src/prefect/engine.py
> +                force=True,
Can we just do `force=task_run.state.is_pending()` with that comment for clarity?

2022-09-17 11:31 UTC, jlowin commented
I agree, REJECT means "you asked to transition to X but you transitioned to Y instead" which isn't the semantic here

2022-09-17 11:34 UTC, jlowin approved these changes

2022-09-19 16:43 UTC, merged