Docs: add the link to Deployment API
PrefectHQ/prefect pull request #7037
Opened 2022-09-30 15:42 UTC by khuyentran1401

When reading the section about creating a deployment from a Python object, I found it difficult to know the possible parameters for the `Deployment` object. So I think it will be helpful to link to the API for the `Deployment` object.

### Example

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

2022-09-30 18:01 UTC, tpdorsey reviewed
Minor suggested edit

2022-09-30 18:01 UTC, tpdorsey commented on docs/concepts/deployments.md
> +View all of the parameters for the `Deployment` object [here](https://docs.prefect.io/api-ref/prefect/deployments/).
```suggestion
View all of the parameters for the `Deployment` object in the [Python API documentation](https://docs.prefect.io/api-ref/prefect/deployments/).
```

2022-09-30 18:02 UTC, tpdorsey commented
@serinamarie this PR also includes adding an item to the recipes catalog. Can you weigh in on this?

2022-09-30 18:18 UTC, serinamarie requested changes
Love this idea and think it would be great to have a list of all available parameters at the ready like this for all our primitives, rather than a user having to go to the search bar again.

2022-09-30 18:18 UTC, serinamarie commented on docs/recipes/catalog/github-docker.yaml
> +recipeName: Deployment with GitHub and Docker
```suggestion
recipeName: Flow Deployment with GitHub Storage and Docker Infrastructure
```

2022-10-03 16:52 UTC, tpdorsey approved these changes

2022-10-03 16:53 UTC, merged