Add custom run feature
PrefectHQ/prefect pull request #8405
Opened 2023-02-03 21:10 UTC by marichka-offen

### Example

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

2023-02-03 21:24 UTC, znicholasbrown requested changes
From sync review

2023-02-03 21:24 UTC, znicholasbrown commented on orion-ui/src/pages/FlowRunCreate.vue
> +  const deploymentSubscription = useSubscriptionWithDependencies(api.deployments.getDeployment, deploymentArgs)
```suggestion
```

2023-02-03 21:24 UTC, znicholasbrown commented on orion-ui/src/pages/FlowRunCreate.vue
> +  const flowRunId = useRouteParam('flowRunId')
```suggestion
  const parameters  = useRouteQueryParam('parameters', VALIDATOR)
```

2023-02-03 21:24 UTC, znicholasbrown commented on orion-ui/src/pages/FlowRunCreate.vue
> +    <FlowRunCreateForm :deployment="deployment" :flow-run="flowRun" @submit="createFlowRun" @cancel="goBack" />
```suggestion
    <FlowRunCreateForm :deployment="deployment" :parameters="parameters" @submit="createFlowRun" @cancel="goBack" />
```

2023-02-03 21:24 UTC, znicholasbrown commented on orion-ui/src/pages/FlowRunCreate.vue
> +  const flowRunId = useRouteParam('flowRunId')
```
{}
```

2023-02-07 21:31 UTC, pleek91 approved these changes

2023-02-07 21:44 UTC, merged

2023-02-15 12:38 UTC, quassy commented
The release notes mention that's it's now possible to create a flow run *from* the UI with parameters from a *previous* run. But I can only find this PR that adds an optional `parameters` to the run URL, no way to actually do that from the UI and also no way to get there from a previous run. Is there something I'm missing or is this not yet deployed on Prefect Cloud?