Docs: Add Resume Flow Run Through UI
PrefectHQ/prefect pull request #8621
Opened 2023-02-22 21:09 UTC by khuyentran1401

The current doc doesn't mention that users can resume the flow run through the UI. This PR adds this utility to the doc. 

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

2023-02-22 22:39 UTC, anna-geller requested changes

2023-02-22 22:39 UTC, anna-geller commented on docs/concepts/flows.md
> +Paused flows can be resumed by clicking the **Resume** button in the Prefect UI or Prefect Cloud or by calling the resume flow run utility in another process.
```suggestion
Paused flow runs can be resumed by clicking the **Resume** button in the Prefect UI or calling the `resume_flow_run` utility via client code.
```

2023-02-22 23:48 UTC, tpdorsey approved these changes

2023-02-23 00:33 UTC, anna-geller approved these changes

2023-02-23 15:07 UTC, billpalombi approved these changes
lgtm

2023-02-23 15:33 UTC, merged