Gab first steps
PrefectHQ/prefect pull request #9456
Opened 2023-05-04 19:17 UTC by gabcoyne

### Example

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

2023-05-05 14:10 UTC, discdiver commented
Sweet! You'll want to add redirects to netlify.toml to avoid 404s, probably with a [splat](https://docs.netlify.com/routing/redirects/redirect-options/#splats)

2023-05-05 14:25 UTC, discdiver requested changes
I'm good with renaming "tutorials" to "tutorial"
- making a new worker was moved from tutorial to guide - merging from main branch should update that
- noted netlifly.toml redirects need created in another comment
- there's a disconnect from having the projects page and then the following step is the deployments page that doesn't mention projects and makes it sound like deployments haven't been introduced. Maybe that's fine while projects are in beta, assuming they move to GA before long. That's not something your changes introduced, just noting it.

2023-05-05 20:03 UTC, gabcoyne commented
@biancaines from the above @discdiver is echoing your concern about order of projects and deployments

2023-05-15 23:26 UTC, serinamarie commented on docs/cloud/cloud-quickstart.md
> +If you're new to Prefect, learn more about writing and running flows in the [Prefect Flows First Steps](/tutorial/first-steps/) tutorial. If you're already familiar with Prefect flows and want to try
```suggestion
If you're new to Prefect, learn more about writing and running flows in the [Prefect Flows First Steps](/tutorial/first-steps/) tutorial. If you're already familiar with Prefect flows and want to try creating deployments and kicking off flow runs with Prefect Cloud, check out the [Deployments](/tutorial/deployments/) and [Storage and Infrastructure](/tutorial/storage/) tutorials.
```

2023-05-15 23:29 UTC, serinamarie commented on docs/cloud/connecting.md
> +See the [Flow orchestration with Prefect](/orchestration/) tutorial for examples.
```suggestion
See the [Flow orchestration with Prefect](/tutorial/orchestration/) tutorial for examples.
```

2023-05-15 23:30 UTC, serinamarie commented on docs/cloud/index.md
> +Prefect Cloud is a workflow coordination-as-a-service platform. Prefect Cloud provides all the capabilities of the [Prefect server](/orchestration/#running-the-prefect-server) and UI in a hosted envi
```suggestion
Prefect Cloud is a workflow coordination-as-a-service platform. Prefect Cloud provides all the capabilities of the [Prefect server](/orchestration/#running-the-prefect-server) and UI in a hosted environment, plus additional features such as automations, workspaces, and organizations.
```
```suggestion
Prefect Cloud is a workflow coordination-as-a-service platform. Prefect Cloud provides all the capabilities of the [Prefect server](/tutorial/orchestration/#running-the-prefect-server) and UI in a hosted environment, plus additional features such as automations, workspaces, and organizations.
```

2023-05-16 00:01 UTC, serinamarie requested changes

2023-05-16 00:15 UTC, gabcoyne commented
@serinamarie All links pass

2023-05-16 21:24 UTC, serinamarie commented on docs/index.md
> +[Concepts](/concepts){ .md-button .main-button--secondary .full } [Tutorials](/){ .md-button .md-button--primary .main-button--primary .full }  [Guides](guides){ .md-button .main-button--secondary .f
@gabcoyne This is still relevant

2023-05-16 21:24 UTC, serinamarie commented on docs/index.md
> +If you're ready to dive in and learn Prefect, check out the Prefect [concepts](/concepts/index/) and try some [tutorials](/) to see how they work in action.
@gabcoyne This is still relevant

2023-05-16 21:25 UTC, serinamarie commented on docs/concepts/projects.md
> +    For an example, [check out the project tutorial](/concepts/projects/#dockerized-deployment).
@gabcoyne This suggestion still needs committing

2023-05-16 21:26 UTC, serinamarie commented on docs/tutorial/developing-a-new-worker-type.md
@gabcoyne I think this guy still needs to be removed from `tutorial` since it's in `guides`

2023-05-16 21:27 UTC, serinamarie commented
@gabcoyne There are a few suggestions that are still relevant

2023-05-18 15:25 UTC, serinamarie approved these changes

2023-05-18 15:25 UTC, discdiver approved these changes

2023-05-18 15:25 UTC, merged