Update Worker Requirements in Projects Tutorial.md
PrefectHQ/prefect pull request #9579
Opened 2023-05-15 20:34 UTC by mattconger

added a line saying it is necessary to have prefect-docker installed for docker type worker

### Example

### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

2023-05-15 20:36 UTC, serinamarie commented on docs/tutorials/projects.md
> +    Each command will automatically create an appropriately typed work pool with default settings. For each type of worker you will need to insall the specific worker from the repo.  For example to s
```suggestion
    Each command will automatically create an appropriately typed work pool with default settings. For each type of worker you will need to insall the specific worker from the repo.  For example, to start the Docker worker you will need to run `pip install prefect-docker`.  
```

2023-05-15 21:16 UTC, billpalombi requested changes

2023-05-15 21:16 UTC, billpalombi commented on docs/tutorials/projects.md
> +    Each command will automatically create an appropriately typed work pool with default settings. For each type of worker you will need to insall the specific worker from the repo.  For example to s
```suggestion
    Each command will automatically create an appropriately typed work pool with default settings. For each type of worker you will need to install the specific worker from the repo.  For example to start the docker worker you will need to pip install prefect-docker.  
```

2023-05-15 21:16 UTC, billpalombi commented on docs/tutorials/projects.md
> +    Each command will automatically create an appropriately typed work pool with default settings. For each type of worker you will need to insall the specific worker from the repo.  For example to s
> the repo

What repo? Do you mean collection?

2023-06-01 17:24 UTC, serinamarie approved these changes

2023-06-01 17:26 UTC, merged