Feature: add Telegram webhook notification support
PrefectHQ/prefect pull request #9825
Opened 2023-06-03 06:25 UTC by mujahidfa

Adds a TelegramWebhook notification block using the AbstractAppriseNotificationBlock.

Closes #9408.

### Example
```python
from prefect.blocks.notifications import TelegramWebhook
from pydantic import SecretStr

telegram_webhook_block = TelegramWebhook(
    bot_token=SecretStr("0123456789:qwertyuiopasdfghjklzxcvbnm"), 
    chat_id="123456789"
)
telegram_webhook_block.notify("Hello from Prefect!")
```

Result:

<img width="466" alt="Telegram chat containing 1 message from test_prefect that says 'Hello from Prefect!'." src="https://github.com/PrefectHQ/prefect/assets/17759705/63af523a-bff9-42df-999e-fd89db7e2233">

### Checklist
- [x] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [x] This pull request includes tests or only affects documentation.
- [x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

2023-06-03 23:05 UTC, madkinsz approved these changes
LGTM! Thanks for contributing!

2023-06-05 16:41 UTC, desertaxle requested changes
Thanks for the contribution! The implementation looks solid! Most of my comments involve making the generated form for this block more intuitive for users. Let me know if you have any questions!

2023-06-05 16:41 UTC, desertaxle commented on src/prefect/blocks/notifications.py
> +    )
```suggestion
    preview: bool = Field(
        default=False,
        description=(
            "Whether to display webpage previews of your post."
        ),
    )
```

2023-06-05 16:41 UTC, desertaxle commented on src/prefect/blocks/notifications.py
> +    )
A `bool` typed field will render nicely in the UI.

```suggestion
    silent: bool = Field(
        default=False,
        description=(
            "Whether to send the notification silently."
        ),
    )
```

2023-06-05 16:41 UTC, desertaxle commented on src/prefect/blocks/notifications.py
> +    topic_id: Optional[SecretStr] = Field(
Is this a sensitive value? It doesn't seem like this needs to be a `SecretStr` and instead could be a `str`.

2023-06-05 16:41 UTC, desertaxle commented on src/prefect/blocks/notifications.py
> +    )
I propose we leave this field off for now since Prefect doesn't currently handle images in notifications.

2023-06-05 16:41 UTC, desertaxle commented on src/prefect/blocks/notifications.py
> +            ).url()
It'd be nice to include the `format` kwarg as well to allow different formatting styles.

2023-08-26 19:01 UTC, closed without merging

2023-12-30 10:02 UTC, DhavalThkkar commented
@mujahidfa @desertaxle Is there any update on this? Expected anytime soon?

2024-06-08 12:55 UTC, jfloodnet commented
Ah that's a shame

2024-08-22 16:37 UTC, 50Bytes-dev commented
UP!

2024-10-14 10:12 UTC, koolvn commented
Oh, come on guys! This PR wasn't merged only because of descriptions?
Community needs the telegram notifications!

2025-02-05 18:49 UTC, baltic-tea commented
UP!!!

I'd like to understand why this feature hasn't been merged yet?

Discuss: https://github.com/PrefectHQ/prefect/discussions/16988