feature: add `infra_overrides` field in `FlowRun`
PrefectHQ/prefect pull request #9894
Opened 2023-06-12 10:50 UTC by usefulalgorithm

### Overview

This PR adds the ability to override infrastructure block's configuration when creating a FlowRun.

Closes #9893 

### Example

```python
import prefect
client = prefect.client.get_client()

parameters = {
    "pathToAFile": "s3://bucket/10G_file"
}
infra_overrides = {
    "customizations": [
        {
           "op": "add",
           "path": "/spec/template/spec/containers/0/resources",
           "value": {
               "requests": {
                   "memory": "10gi"
               }
            }
         }
    ]
}

flow_run = client.create_flow_run_from_deployment(..., parameters=parameters, infra_overrides=infra_overrides)

# ...

parameters = {
    "pathToAFile": "s3://bucket/1K_file"
}
infra_overrides = {
    "customizations": [
        {
           "op": "add",
           "path": "/spec/template/spec/containers/0/resources",
           "value": {
               "requests": {
                   "memory": "1ki"
               }
            }
         }
    ]
}
another_flow_run = client.create_flow_run_from_deployment(..., parameters=parameters, infra_overrides=infra_overrides)
```
### Checklist

- [ ] This pull request references any related issue by including "closes `<link to issue>`"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

2023-06-13 18:23 UTC, chrisguidry requested changes
Thanks for starting a contribution, @usefulalgorithm!

We generally require new unit tests for any new functionality.  

Additionally, these changes don't include the model/database changes that would be required to persist this information across time.  This means that when a later worker or agent picks up this flow run, it won't retain the `infra_overrides` attribute.  To persist the changes, you'd need to [update the ORM model](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/database/orm_models.py#L480) and create the associated database migrations.  

We would also need to coordinate this change with Prefect Cloud, so that the [Prefect Cloud compatibility tests](https://github.com/PrefectHQ/compat-tests) pass.

2023-06-15 10:20 UTC, usefulalgorithm commented
Hi @chrisguidry , thanks for the feedback!

> We generally require new unit tests for any new functionality.

I did a unit test to ensure that `create_flow_run_from_deployment` does indeed take `infra_overrides` as a valid parameter on the server side.

>Additionally, these changes don't include the model/database changes that would be required to persist this information across time. This means that when a later worker or agent picks up this flow run, it won't retain the infra_overrides attribute. To persist the changes, you'd need to [update the ORM model](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/database/orm_models.py#L480) and create the associated database migrations.

I added the migration scripts as you suggested, not sure how to test these though...

> We would also need to coordinate this change with Prefect Cloud, so that the [Prefect Cloud compatibility tests](https://github.com/PrefectHQ/compat-tests) pass.

Can you provide me with a pointer or two on how to do this? Can't really tell what I need to do just by looking at the repository you provided.

Thanks again!

2023-06-15 13:52 UTC, chrisguidry commented
Ah sorry I wasn't clear: We (the Prefect team) will handle the Prefect Cloud side of this and so we can catch up the compatibility tests.  Once this PR is tightened up and passing tests, I'll help find a maintainer that can help with that.

Regarding testing of the migration and persistence, your migrations will be tested by running all of the CI tests that run as part of our Github actions, so that part doesn't require any additional testing of the migration on your end.

Testing the persistence would need a test that demonstrates that you can create a flow run with `infra_overrides` and then retrieve it again to demonstrate that they are returned.  I think a test in `tests/server/api/test_flow_runs.py` that creates a flow run with a `POST` request, then retrieves it again with a `GET` request would do the trick.

2023-06-16 03:31 UTC, usefulalgorithm commented on src/prefect/agent.py
> +        # FlowRun's infra_overrides should take precedence over Deployment's
I think this should be the only thing to change in order to make `FlowRun`'s `infra_overrides` override `Deployment`'s, right?

2023-06-16 03:38 UTC, usefulalgorithm commented on src/prefect/server/api/deployments.py
> +        infra_overrides = deployment.infra_overrides
I guess I don't need to do this...

2023-06-16 03:39 UTC, usefulalgorithm commented on src/prefect/server/api/deployments.py
> +                    "infra_overrides",
... and this? Since in agent it actually resolves the 2 dicts

2023-06-21 05:04 UTC, usefulalgorithm commented
bump

2023-06-28 05:04 UTC, usefulalgorithm commented
Hi @zangell44 , sorry for the noise but can you take a look at this one when you have a moment? I created an [issue](https://github.com/PrefectHQ/prefect/issues/9893) just like the contribution guide suggested, but it's been stuck at triage for about 2 weeks now. No one seemed to have reviewed the issue and the functionality proposed in it.

If the feature I'm trying to implement is not what the team would consider, or if there's any other plan for this, please also let me know.

Thank you!

2023-06-29 09:03 UTC, ianccy commented
@chrisguidry SOS

2023-06-30 03:37 UTC, usefulalgorithm commented
thanks!

2023-08-17 06:28 UTC, yuwaj6 commented
Hi @chrisguidry,
It's been a while since we heard back from you. 
Let us know if there's something we can do to prioritize this pull request.

Thanks!

2023-08-22 17:26 UTC, closed without merging

2023-08-23 05:08 UTC, usefulalgorithm commented
no worries, thanks for the response!